2022-05-03 21:19:40,636:INFO:PyCaret Supervised Module
2022-05-03 21:19:40,637:INFO:ML Usecase: regression
2022-05-03 21:19:40,637:INFO:version 2.3.6
2022-05-03 21:19:40,638:INFO:Initializing setup()
2022-05-03 21:19:40,638:INFO:setup(target=interest_rate, ml_usecase=regression, available_plots={'parameter': 'Hyperparameters', 'residuals': 'Residuals', 'error': 'Prediction Error', 'cooks': 'Cooks Distance', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'vc': 'Validation Curve', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'tree': 'Decision Tree', 'residuals_interactive': 'Interactive Residuals'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=kfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-05-03 21:19:40,639:INFO:Checking environment
2022-05-03 21:19:40,639:INFO:python_version: 3.8.12
2022-05-03 21:19:40,639:INFO:python_build: ('default', 'Oct 12 2021 03:01:40')
2022-05-03 21:19:40,640:INFO:machine: AMD64
2022-05-03 21:19:40,640:INFO:platform: Windows-10-10.0.19044-SP0
2022-05-03 21:19:40,644:WARNING:cannot find psutil installation. memory not traceable. Install psutil using pip to enable memory logging.
2022-05-03 21:19:40,644:INFO:Checking libraries
2022-05-03 21:19:40,645:INFO:pd==1.4.1
2022-05-03 21:19:40,645:INFO:numpy==1.19.5
2022-05-03 21:19:40,645:INFO:sklearn==0.23.2
2022-05-03 21:19:40,646:INFO:lightgbm==3.3.2
2022-05-03 21:19:40,649:WARNING:catboost not found
2022-05-03 21:19:40,650:WARNING:xgboost not found
2022-05-03 21:19:52,754:INFO:mlflow==1.24.0
2022-05-03 21:19:52,755:INFO:Checking Exceptions
2022-05-03 21:19:52,755:INFO:Declaring global variables
2022-05-03 21:19:52,755:INFO:USI: c829
2022-05-03 21:19:52,756:INFO:pycaret_globals: {'_gpu_n_jobs_param', 'imputation_classifier', 'X_train', 'fix_imbalance_method_param', 'master_model_container', 'data_before_preprocess', 'html_param', 'y', '_all_metrics', 'exp_name_log', 'X_test', 'fold_generator', 'prep_pipe', 'y_test', 'logging_param', '_available_plots', 'target_param', 'seed', 'fold_groups_param_full', 'create_model_container', 'fold_groups_param', 'iterative_imputation_iters_param', 'experiment__', '_ml_usecase', 'fold_param', '_all_models_internal', 'USI', 'log_plots_param', '_all_models', 'n_jobs_param', 'pycaret_globals', 'imputation_regressor', 'display_container', 'fold_shuffle_param', 'stratify_param', 'transform_target_method_param', 'y_train', 'fix_imbalance_param', '_internal_pipeline', 'gpu_param', 'X', 'transform_target_param'}
2022-05-03 21:19:52,756:INFO:Preparing display monitor
2022-05-03 21:19:52,756:INFO:Preparing display monitor
2022-05-03 21:19:52,806:INFO:Importing libraries
2022-05-03 21:19:52,807:INFO:Copying data for preprocessing
2022-05-03 21:19:52,929:INFO:Declaring preprocessing parameters
2022-05-03 21:19:52,938:INFO:Creating preprocessing pipeline
2022-05-03 21:19:53,517:INFO:Preprocessing pipeline created successfully
2022-05-03 21:19:53,517:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-05-03 21:19:53,517:INFO:Creating global containers
2022-05-03 21:19:53,542:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2022-05-03 21:20:59,480:WARNING:Couldn't import xgboost.XGBRegressor
2022-05-03 21:20:59,487:WARNING:Couldn't import catboost.CatBoostRegressor
2022-05-03 21:21:00,280:WARNING:Couldn't import xgboost.XGBRegressor
2022-05-03 21:21:00,283:WARNING:Couldn't import catboost.CatBoostRegressor
2022-05-03 21:21:00,287:INFO:Creating grid variables
2022-05-03 21:21:00,335:INFO:create_model_container: 0
2022-05-03 21:21:00,335:INFO:master_model_container: 0
2022-05-03 21:21:00,336:INFO:display_container: 1
2022-05-03 21:21:00,370:INFO:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[], ml_usecase='regression',
                                      numerical_features=[],
                                      target='interest_rate',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_st...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='interest_rate')),
                ('fix_perfect', Remove_100(target='interest_rate')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)
2022-05-03 21:21:00,370:INFO:setup() succesfully completed......................................
2022-05-03 21:21:08,733:INFO:Initializing compare_models()
2022-05-03 21:21:08,733:INFO:compare_models(include=None, fold=None, round=4, cross_validation=True, sort=R2, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, probability_threshold=None, verbose=True, display=None, exclude=None)
2022-05-03 21:21:08,733:INFO:Checking exceptions
2022-05-03 21:21:08,733:INFO:Preparing display monitor
2022-05-03 21:21:08,734:INFO:Preparing display monitor
2022-05-03 21:21:08,808:INFO:Initializing Linear Regression
2022-05-03 21:21:08,808:INFO:Total runtime is 0.0 minutes
2022-05-03 21:21:08,847:INFO:SubProcess create_model() called ==================================
2022-05-03 21:21:08,848:INFO:Initializing create_model()
2022-05-03 21:21:08,848:INFO:create_model(estimator=lr, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:21:08,848:INFO:Checking exceptions
2022-05-03 21:21:08,848:INFO:Importing libraries
2022-05-03 21:21:08,848:INFO:Copying training dataset
2022-05-03 21:21:08,851:INFO:Defining folds
2022-05-03 21:21:08,851:INFO:Declaring metric variables
2022-05-03 21:21:08,899:INFO:Importing untrained model
2022-05-03 21:21:08,933:INFO:Linear Regression Imported succesfully
2022-05-03 21:21:08,990:INFO:Starting cross validation
2022-05-03 21:21:09,027:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:21:37,884:INFO:Calculating mean and std
2022-05-03 21:21:37,888:INFO:Creating metrics dataframe
2022-05-03 21:21:38,096:INFO:Uploading results into container
2022-05-03 21:21:38,096:INFO:Uploading model into container now
2022-05-03 21:21:38,097:INFO:create_model_container: 1
2022-05-03 21:21:38,097:INFO:master_model_container: 1
2022-05-03 21:21:38,097:INFO:display_container: 2
2022-05-03 21:21:38,098:INFO:LinearRegression(copy_X=True, fit_intercept=True, n_jobs=-1, normalize=False)
2022-05-03 21:21:38,098:INFO:create_model() succesfully completed......................................
2022-05-03 21:21:38,569:INFO:SubProcess create_model() end ==================================
2022-05-03 21:21:38,569:INFO:Creating metrics dataframe
2022-05-03 21:21:38,663:INFO:Initializing Lasso Regression
2022-05-03 21:21:38,664:INFO:Total runtime is 0.4976010044415792 minutes
2022-05-03 21:21:38,693:INFO:SubProcess create_model() called ==================================
2022-05-03 21:21:38,694:INFO:Initializing create_model()
2022-05-03 21:21:38,694:INFO:create_model(estimator=lasso, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:21:38,695:INFO:Checking exceptions
2022-05-03 21:21:38,695:INFO:Importing libraries
2022-05-03 21:21:38,696:INFO:Copying training dataset
2022-05-03 21:21:38,699:INFO:Defining folds
2022-05-03 21:21:38,699:INFO:Declaring metric variables
2022-05-03 21:21:38,724:INFO:Importing untrained model
2022-05-03 21:21:38,749:INFO:Lasso Regression Imported succesfully
2022-05-03 21:21:38,803:INFO:Starting cross validation
2022-05-03 21:21:38,804:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:21:39,483:INFO:Calculating mean and std
2022-05-03 21:21:39,485:INFO:Creating metrics dataframe
2022-05-03 21:21:39,613:INFO:Uploading results into container
2022-05-03 21:21:39,614:INFO:Uploading model into container now
2022-05-03 21:21:39,614:INFO:create_model_container: 2
2022-05-03 21:21:39,614:INFO:master_model_container: 2
2022-05-03 21:21:39,614:INFO:display_container: 2
2022-05-03 21:21:39,637:INFO:Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=3515,
      selection='cyclic', tol=0.0001, warm_start=False)
2022-05-03 21:21:39,637:INFO:create_model() succesfully completed......................................
2022-05-03 21:21:40,097:INFO:SubProcess create_model() end ==================================
2022-05-03 21:21:40,098:INFO:Creating metrics dataframe
2022-05-03 21:21:40,198:INFO:Initializing Ridge Regression
2022-05-03 21:21:40,198:INFO:Total runtime is 0.5231696605682373 minutes
2022-05-03 21:21:40,229:INFO:SubProcess create_model() called ==================================
2022-05-03 21:21:40,230:INFO:Initializing create_model()
2022-05-03 21:21:40,231:INFO:create_model(estimator=ridge, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:21:40,231:INFO:Checking exceptions
2022-05-03 21:21:40,231:INFO:Importing libraries
2022-05-03 21:21:40,231:INFO:Copying training dataset
2022-05-03 21:21:40,234:INFO:Defining folds
2022-05-03 21:21:40,238:INFO:Declaring metric variables
2022-05-03 21:21:40,257:INFO:Importing untrained model
2022-05-03 21:21:40,285:INFO:Ridge Regression Imported succesfully
2022-05-03 21:21:40,333:INFO:Starting cross validation
2022-05-03 21:21:40,335:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:21:40,838:INFO:Calculating mean and std
2022-05-03 21:21:40,841:INFO:Creating metrics dataframe
2022-05-03 21:21:40,992:INFO:Uploading results into container
2022-05-03 21:21:40,993:INFO:Uploading model into container now
2022-05-03 21:21:40,993:INFO:create_model_container: 3
2022-05-03 21:21:40,993:INFO:master_model_container: 3
2022-05-03 21:21:40,993:INFO:display_container: 2
2022-05-03 21:21:40,994:INFO:Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=3515, solver='auto', tol=0.001)
2022-05-03 21:21:40,994:INFO:create_model() succesfully completed......................................
2022-05-03 21:21:41,442:INFO:SubProcess create_model() end ==================================
2022-05-03 21:21:41,443:INFO:Creating metrics dataframe
2022-05-03 21:21:41,550:INFO:Initializing Elastic Net
2022-05-03 21:21:41,551:INFO:Total runtime is 0.5457067171732585 minutes
2022-05-03 21:21:41,573:INFO:SubProcess create_model() called ==================================
2022-05-03 21:21:41,575:INFO:Initializing create_model()
2022-05-03 21:21:41,575:INFO:create_model(estimator=en, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:21:41,575:INFO:Checking exceptions
2022-05-03 21:21:41,575:INFO:Importing libraries
2022-05-03 21:21:41,576:INFO:Copying training dataset
2022-05-03 21:21:41,580:INFO:Defining folds
2022-05-03 21:21:41,580:INFO:Declaring metric variables
2022-05-03 21:21:41,603:INFO:Importing untrained model
2022-05-03 21:21:41,634:INFO:Elastic Net Imported succesfully
2022-05-03 21:21:41,680:INFO:Starting cross validation
2022-05-03 21:21:41,681:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:21:42,322:INFO:Calculating mean and std
2022-05-03 21:21:42,324:INFO:Creating metrics dataframe
2022-05-03 21:21:42,446:INFO:Uploading results into container
2022-05-03 21:21:42,447:INFO:Uploading model into container now
2022-05-03 21:21:42,447:INFO:create_model_container: 4
2022-05-03 21:21:42,447:INFO:master_model_container: 4
2022-05-03 21:21:42,448:INFO:display_container: 2
2022-05-03 21:21:42,449:INFO:ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=3515, selection='cyclic', tol=0.0001, warm_start=False)
2022-05-03 21:21:42,449:INFO:create_model() succesfully completed......................................
2022-05-03 21:21:42,992:INFO:SubProcess create_model() end ==================================
2022-05-03 21:21:42,992:INFO:Creating metrics dataframe
2022-05-03 21:21:43,087:INFO:Initializing Least Angle Regression
2022-05-03 21:21:43,088:INFO:Total runtime is 0.5713342467943827 minutes
2022-05-03 21:21:43,124:INFO:SubProcess create_model() called ==================================
2022-05-03 21:21:43,125:INFO:Initializing create_model()
2022-05-03 21:21:43,125:INFO:create_model(estimator=lar, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:21:43,125:INFO:Checking exceptions
2022-05-03 21:21:43,125:INFO:Importing libraries
2022-05-03 21:21:43,126:INFO:Copying training dataset
2022-05-03 21:21:43,128:INFO:Defining folds
2022-05-03 21:21:43,129:INFO:Declaring metric variables
2022-05-03 21:21:43,156:INFO:Importing untrained model
2022-05-03 21:21:43,180:INFO:Least Angle Regression Imported succesfully
2022-05-03 21:21:43,246:INFO:Starting cross validation
2022-05-03 21:21:43,249:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:21:43,950:INFO:Calculating mean and std
2022-05-03 21:21:43,952:INFO:Creating metrics dataframe
2022-05-03 21:21:44,074:INFO:Uploading results into container
2022-05-03 21:21:44,074:INFO:Uploading model into container now
2022-05-03 21:21:44,074:INFO:create_model_container: 5
2022-05-03 21:21:44,075:INFO:master_model_container: 5
2022-05-03 21:21:44,075:INFO:display_container: 2
2022-05-03 21:21:44,076:INFO:Lars(copy_X=True, eps=2.220446049250313e-16, fit_intercept=True, fit_path=True,
     jitter=None, n_nonzero_coefs=500, normalize=True, precompute='auto',
     random_state=3515, verbose=False)
2022-05-03 21:21:44,076:INFO:create_model() succesfully completed......................................
2022-05-03 21:21:44,461:INFO:SubProcess create_model() end ==================================
2022-05-03 21:21:44,462:INFO:Creating metrics dataframe
2022-05-03 21:21:44,563:INFO:Initializing Lasso Least Angle Regression
2022-05-03 21:21:44,563:INFO:Total runtime is 0.5959201137224833 minutes
2022-05-03 21:21:44,589:INFO:SubProcess create_model() called ==================================
2022-05-03 21:21:44,590:INFO:Initializing create_model()
2022-05-03 21:21:44,590:INFO:create_model(estimator=llar, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:21:44,590:INFO:Checking exceptions
2022-05-03 21:21:44,590:INFO:Importing libraries
2022-05-03 21:21:44,591:INFO:Copying training dataset
2022-05-03 21:21:44,593:INFO:Defining folds
2022-05-03 21:21:44,594:INFO:Declaring metric variables
2022-05-03 21:21:44,622:INFO:Importing untrained model
2022-05-03 21:21:44,649:INFO:Lasso Least Angle Regression Imported succesfully
2022-05-03 21:21:44,696:INFO:Starting cross validation
2022-05-03 21:21:44,697:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:21:45,230:INFO:Calculating mean and std
2022-05-03 21:21:45,238:INFO:Creating metrics dataframe
2022-05-03 21:21:45,366:INFO:Uploading results into container
2022-05-03 21:21:45,366:INFO:Uploading model into container now
2022-05-03 21:21:45,367:INFO:create_model_container: 6
2022-05-03 21:21:45,367:INFO:master_model_container: 6
2022-05-03 21:21:45,367:INFO:display_container: 2
2022-05-03 21:21:45,368:INFO:LassoLars(alpha=1.0, copy_X=True, eps=2.220446049250313e-16, fit_intercept=True,
          fit_path=True, jitter=None, max_iter=500, normalize=True,
          positive=False, precompute='auto', random_state=3515, verbose=False)
2022-05-03 21:21:45,369:INFO:create_model() succesfully completed......................................
2022-05-03 21:21:45,796:INFO:SubProcess create_model() end ==================================
2022-05-03 21:21:45,797:INFO:Creating metrics dataframe
2022-05-03 21:21:45,913:INFO:Initializing Orthogonal Matching Pursuit
2022-05-03 21:21:45,913:INFO:Total runtime is 0.6184072097142538 minutes
2022-05-03 21:21:45,936:INFO:SubProcess create_model() called ==================================
2022-05-03 21:21:45,937:INFO:Initializing create_model()
2022-05-03 21:21:45,938:INFO:create_model(estimator=omp, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:21:45,938:INFO:Checking exceptions
2022-05-03 21:21:45,938:INFO:Importing libraries
2022-05-03 21:21:45,938:INFO:Copying training dataset
2022-05-03 21:21:45,941:INFO:Defining folds
2022-05-03 21:21:45,941:INFO:Declaring metric variables
2022-05-03 21:21:45,970:INFO:Importing untrained model
2022-05-03 21:21:45,993:INFO:Orthogonal Matching Pursuit Imported succesfully
2022-05-03 21:21:46,047:INFO:Starting cross validation
2022-05-03 21:21:46,048:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:21:46,557:INFO:Calculating mean and std
2022-05-03 21:21:46,565:INFO:Creating metrics dataframe
2022-05-03 21:21:46,692:INFO:Uploading results into container
2022-05-03 21:21:46,693:INFO:Uploading model into container now
2022-05-03 21:21:46,693:INFO:create_model_container: 7
2022-05-03 21:21:46,693:INFO:master_model_container: 7
2022-05-03 21:21:46,694:INFO:display_container: 2
2022-05-03 21:21:46,694:INFO:OrthogonalMatchingPursuit(fit_intercept=True, n_nonzero_coefs=None,
                          normalize=True, precompute='auto', tol=None)
2022-05-03 21:21:46,694:INFO:create_model() succesfully completed......................................
2022-05-03 21:21:47,117:INFO:SubProcess create_model() end ==================================
2022-05-03 21:21:47,117:INFO:Creating metrics dataframe
2022-05-03 21:21:47,241:INFO:Initializing Bayesian Ridge
2022-05-03 21:21:47,241:INFO:Total runtime is 0.6405530452728272 minutes
2022-05-03 21:21:47,273:INFO:SubProcess create_model() called ==================================
2022-05-03 21:21:47,274:INFO:Initializing create_model()
2022-05-03 21:21:47,274:INFO:create_model(estimator=br, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:21:47,274:INFO:Checking exceptions
2022-05-03 21:21:47,275:INFO:Importing libraries
2022-05-03 21:21:47,275:INFO:Copying training dataset
2022-05-03 21:21:47,278:INFO:Defining folds
2022-05-03 21:21:47,278:INFO:Declaring metric variables
2022-05-03 21:21:47,325:INFO:Importing untrained model
2022-05-03 21:21:47,367:INFO:Bayesian Ridge Imported succesfully
2022-05-03 21:21:47,464:INFO:Starting cross validation
2022-05-03 21:21:47,467:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:21:48,841:INFO:Calculating mean and std
2022-05-03 21:21:48,846:INFO:Creating metrics dataframe
2022-05-03 21:21:49,023:INFO:Uploading results into container
2022-05-03 21:21:49,024:INFO:Uploading model into container now
2022-05-03 21:21:49,025:INFO:create_model_container: 8
2022-05-03 21:21:49,025:INFO:master_model_container: 8
2022-05-03 21:21:49,025:INFO:display_container: 2
2022-05-03 21:21:49,027:INFO:BayesianRidge(alpha_1=1e-06, alpha_2=1e-06, alpha_init=None,
              compute_score=False, copy_X=True, fit_intercept=True,
              lambda_1=1e-06, lambda_2=1e-06, lambda_init=None, n_iter=300,
              normalize=False, tol=0.001, verbose=False)
2022-05-03 21:21:49,027:INFO:create_model() succesfully completed......................................
2022-05-03 21:21:49,745:INFO:SubProcess create_model() end ==================================
2022-05-03 21:21:49,746:INFO:Creating metrics dataframe
2022-05-03 21:21:50,011:INFO:Initializing Passive Aggressive Regressor
2022-05-03 21:21:50,011:INFO:Total runtime is 0.6867101867993674 minutes
2022-05-03 21:21:50,062:INFO:SubProcess create_model() called ==================================
2022-05-03 21:21:50,062:INFO:Initializing create_model()
2022-05-03 21:21:50,062:INFO:create_model(estimator=par, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:21:50,063:INFO:Checking exceptions
2022-05-03 21:21:50,063:INFO:Importing libraries
2022-05-03 21:21:50,063:INFO:Copying training dataset
2022-05-03 21:21:50,065:INFO:Defining folds
2022-05-03 21:21:50,067:INFO:Declaring metric variables
2022-05-03 21:21:50,091:INFO:Importing untrained model
2022-05-03 21:21:50,142:INFO:Passive Aggressive Regressor Imported succesfully
2022-05-03 21:21:50,201:INFO:Starting cross validation
2022-05-03 21:21:50,204:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:21:52,060:INFO:Calculating mean and std
2022-05-03 21:21:52,065:INFO:Creating metrics dataframe
2022-05-03 21:21:52,243:INFO:Uploading results into container
2022-05-03 21:21:52,243:INFO:Uploading model into container now
2022-05-03 21:21:52,243:INFO:create_model_container: 9
2022-05-03 21:21:52,243:INFO:master_model_container: 9
2022-05-03 21:21:52,243:INFO:display_container: 2
2022-05-03 21:21:52,246:INFO:PassiveAggressiveRegressor(C=1.0, average=False, early_stopping=False,
                           epsilon=0.1, fit_intercept=True,
                           loss='epsilon_insensitive', max_iter=1000,
                           n_iter_no_change=5, random_state=3515, shuffle=True,
                           tol=0.001, validation_fraction=0.1, verbose=0,
                           warm_start=False)
2022-05-03 21:21:52,246:INFO:create_model() succesfully completed......................................
2022-05-03 21:21:53,071:INFO:SubProcess create_model() end ==================================
2022-05-03 21:21:53,072:INFO:Creating metrics dataframe
2022-05-03 21:21:53,392:INFO:Initializing Huber Regressor
2022-05-03 21:21:53,393:INFO:Total runtime is 0.7430778145790101 minutes
2022-05-03 21:21:53,418:INFO:SubProcess create_model() called ==================================
2022-05-03 21:21:53,419:INFO:Initializing create_model()
2022-05-03 21:21:53,419:INFO:create_model(estimator=huber, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:21:53,420:INFO:Checking exceptions
2022-05-03 21:21:53,420:INFO:Importing libraries
2022-05-03 21:21:53,420:INFO:Copying training dataset
2022-05-03 21:21:53,424:INFO:Defining folds
2022-05-03 21:21:53,425:INFO:Declaring metric variables
2022-05-03 21:21:53,458:INFO:Importing untrained model
2022-05-03 21:21:53,481:INFO:Huber Regressor Imported succesfully
2022-05-03 21:21:53,551:INFO:Starting cross validation
2022-05-03 21:21:53,553:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:22:11,585:INFO:Calculating mean and std
2022-05-03 21:22:11,587:INFO:Creating metrics dataframe
2022-05-03 21:22:11,730:INFO:Uploading results into container
2022-05-03 21:22:11,731:INFO:Uploading model into container now
2022-05-03 21:22:11,731:INFO:create_model_container: 10
2022-05-03 21:22:11,731:INFO:master_model_container: 10
2022-05-03 21:22:11,747:INFO:display_container: 2
2022-05-03 21:22:11,748:INFO:HuberRegressor(alpha=0.0001, epsilon=1.35, fit_intercept=True, max_iter=100,
               tol=1e-05, warm_start=False)
2022-05-03 21:22:11,748:INFO:create_model() succesfully completed......................................
2022-05-03 21:22:12,158:INFO:SubProcess create_model() end ==================================
2022-05-03 21:22:12,159:INFO:Creating metrics dataframe
2022-05-03 21:22:12,254:INFO:Initializing K Neighbors Regressor
2022-05-03 21:22:12,254:INFO:Total runtime is 1.057423007488251 minutes
2022-05-03 21:22:12,294:INFO:SubProcess create_model() called ==================================
2022-05-03 21:22:12,295:INFO:Initializing create_model()
2022-05-03 21:22:12,295:INFO:create_model(estimator=knn, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:22:12,298:INFO:Checking exceptions
2022-05-03 21:22:12,299:INFO:Importing libraries
2022-05-03 21:22:12,299:INFO:Copying training dataset
2022-05-03 21:22:12,302:INFO:Defining folds
2022-05-03 21:22:12,302:INFO:Declaring metric variables
2022-05-03 21:22:12,329:INFO:Importing untrained model
2022-05-03 21:22:12,408:INFO:K Neighbors Regressor Imported succesfully
2022-05-03 21:22:12,535:INFO:Starting cross validation
2022-05-03 21:22:12,540:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:22:15,851:INFO:Calculating mean and std
2022-05-03 21:22:15,855:INFO:Creating metrics dataframe
2022-05-03 21:22:16,065:INFO:Uploading results into container
2022-05-03 21:22:16,066:INFO:Uploading model into container now
2022-05-03 21:22:16,066:INFO:create_model_container: 11
2022-05-03 21:22:16,066:INFO:master_model_container: 11
2022-05-03 21:22:16,066:INFO:display_container: 2
2022-05-03 21:22:16,067:INFO:KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                    weights='uniform')
2022-05-03 21:22:16,067:INFO:create_model() succesfully completed......................................
2022-05-03 21:22:16,578:INFO:SubProcess create_model() end ==================================
2022-05-03 21:22:16,578:INFO:Creating metrics dataframe
2022-05-03 21:22:16,751:INFO:Initializing Decision Tree Regressor
2022-05-03 21:22:16,751:INFO:Total runtime is 1.132380302747091 minutes
2022-05-03 21:22:16,786:INFO:SubProcess create_model() called ==================================
2022-05-03 21:22:16,787:INFO:Initializing create_model()
2022-05-03 21:22:16,787:INFO:create_model(estimator=dt, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:22:16,787:INFO:Checking exceptions
2022-05-03 21:22:16,788:INFO:Importing libraries
2022-05-03 21:22:16,788:INFO:Copying training dataset
2022-05-03 21:22:16,791:INFO:Defining folds
2022-05-03 21:22:16,791:INFO:Declaring metric variables
2022-05-03 21:22:16,815:INFO:Importing untrained model
2022-05-03 21:22:16,849:INFO:Decision Tree Regressor Imported succesfully
2022-05-03 21:22:16,908:INFO:Starting cross validation
2022-05-03 21:22:16,910:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:22:18,843:INFO:Calculating mean and std
2022-05-03 21:22:18,845:INFO:Creating metrics dataframe
2022-05-03 21:22:18,952:INFO:Uploading results into container
2022-05-03 21:22:18,952:INFO:Uploading model into container now
2022-05-03 21:22:18,952:INFO:create_model_container: 12
2022-05-03 21:22:18,952:INFO:master_model_container: 12
2022-05-03 21:22:18,953:INFO:display_container: 2
2022-05-03 21:22:18,954:INFO:DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=3515, splitter='best')
2022-05-03 21:22:18,954:INFO:create_model() succesfully completed......................................
2022-05-03 21:22:19,436:INFO:SubProcess create_model() end ==================================
2022-05-03 21:22:19,439:INFO:Creating metrics dataframe
2022-05-03 21:22:19,540:INFO:Initializing Random Forest Regressor
2022-05-03 21:22:19,541:INFO:Total runtime is 1.1788869222005212 minutes
2022-05-03 21:22:19,569:INFO:SubProcess create_model() called ==================================
2022-05-03 21:22:19,570:INFO:Initializing create_model()
2022-05-03 21:22:19,573:INFO:create_model(estimator=rf, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:22:19,573:INFO:Checking exceptions
2022-05-03 21:22:19,573:INFO:Importing libraries
2022-05-03 21:22:19,573:INFO:Copying training dataset
2022-05-03 21:22:19,576:INFO:Defining folds
2022-05-03 21:22:19,577:INFO:Declaring metric variables
2022-05-03 21:22:19,658:INFO:Importing untrained model
2022-05-03 21:22:19,715:INFO:Random Forest Regressor Imported succesfully
2022-05-03 21:22:19,779:INFO:Starting cross validation
2022-05-03 21:22:19,782:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:23:07,718:INFO:Calculating mean and std
2022-05-03 21:23:07,721:INFO:Creating metrics dataframe
2022-05-03 21:23:07,873:INFO:Uploading results into container
2022-05-03 21:23:07,874:INFO:Uploading model into container now
2022-05-03 21:23:07,874:INFO:create_model_container: 13
2022-05-03 21:23:07,874:INFO:master_model_container: 13
2022-05-03 21:23:07,874:INFO:display_container: 2
2022-05-03 21:23:07,875:INFO:RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=-1, oob_score=False,
                      random_state=3515, verbose=0, warm_start=False)
2022-05-03 21:23:07,876:INFO:create_model() succesfully completed......................................
2022-05-03 21:23:08,298:INFO:SubProcess create_model() end ==================================
2022-05-03 21:23:08,298:INFO:Creating metrics dataframe
2022-05-03 21:23:08,427:INFO:Initializing Extra Trees Regressor
2022-05-03 21:23:08,427:INFO:Total runtime is 1.993640796343486 minutes
2022-05-03 21:23:08,471:INFO:SubProcess create_model() called ==================================
2022-05-03 21:23:08,472:INFO:Initializing create_model()
2022-05-03 21:23:08,472:INFO:create_model(estimator=et, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:23:08,472:INFO:Checking exceptions
2022-05-03 21:23:08,473:INFO:Importing libraries
2022-05-03 21:23:08,473:INFO:Copying training dataset
2022-05-03 21:23:08,476:INFO:Defining folds
2022-05-03 21:23:08,476:INFO:Declaring metric variables
2022-05-03 21:23:08,501:INFO:Importing untrained model
2022-05-03 21:23:08,527:INFO:Extra Trees Regressor Imported succesfully
2022-05-03 21:23:08,616:INFO:Starting cross validation
2022-05-03 21:23:08,617:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:23:51,316:INFO:Calculating mean and std
2022-05-03 21:23:51,319:INFO:Creating metrics dataframe
2022-05-03 21:23:51,629:INFO:Uploading results into container
2022-05-03 21:23:51,632:INFO:Uploading model into container now
2022-05-03 21:23:51,632:INFO:create_model_container: 14
2022-05-03 21:23:51,632:INFO:master_model_container: 14
2022-05-03 21:23:51,632:INFO:display_container: 2
2022-05-03 21:23:51,634:INFO:ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                    max_depth=None, max_features='auto', max_leaf_nodes=None,
                    max_samples=None, min_impurity_decrease=0.0,
                    min_impurity_split=None, min_samples_leaf=1,
                    min_samples_split=2, min_weight_fraction_leaf=0.0,
                    n_estimators=100, n_jobs=-1, oob_score=False,
                    random_state=3515, verbose=0, warm_start=False)
2022-05-03 21:23:51,635:INFO:create_model() succesfully completed......................................
2022-05-03 21:23:52,529:INFO:SubProcess create_model() end ==================================
2022-05-03 21:23:52,533:INFO:Creating metrics dataframe
2022-05-03 21:23:52,764:INFO:Initializing AdaBoost Regressor
2022-05-03 21:23:52,770:INFO:Total runtime is 2.7326938033103945 minutes
2022-05-03 21:23:52,943:INFO:SubProcess create_model() called ==================================
2022-05-03 21:23:52,944:INFO:Initializing create_model()
2022-05-03 21:23:52,944:INFO:create_model(estimator=ada, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:23:52,945:INFO:Checking exceptions
2022-05-03 21:23:52,946:INFO:Importing libraries
2022-05-03 21:23:52,946:INFO:Copying training dataset
2022-05-03 21:23:52,949:INFO:Defining folds
2022-05-03 21:23:52,950:INFO:Declaring metric variables
2022-05-03 21:23:52,976:INFO:Importing untrained model
2022-05-03 21:23:53,017:INFO:AdaBoost Regressor Imported succesfully
2022-05-03 21:23:53,076:INFO:Starting cross validation
2022-05-03 21:23:53,078:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:24:19,684:INFO:Calculating mean and std
2022-05-03 21:24:19,689:INFO:Creating metrics dataframe
2022-05-03 21:24:19,812:INFO:Uploading results into container
2022-05-03 21:24:19,813:INFO:Uploading model into container now
2022-05-03 21:24:19,813:INFO:create_model_container: 15
2022-05-03 21:24:19,813:INFO:master_model_container: 15
2022-05-03 21:24:19,813:INFO:display_container: 2
2022-05-03 21:24:19,814:INFO:AdaBoostRegressor(base_estimator=None, learning_rate=1.0, loss='linear',
                  n_estimators=50, random_state=3515)
2022-05-03 21:24:19,814:INFO:create_model() succesfully completed......................................
2022-05-03 21:24:20,404:INFO:SubProcess create_model() end ==================================
2022-05-03 21:24:20,404:INFO:Creating metrics dataframe
2022-05-03 21:24:20,611:INFO:Initializing Gradient Boosting Regressor
2022-05-03 21:24:20,612:INFO:Total runtime is 3.196726083755493 minutes
2022-05-03 21:24:20,646:INFO:SubProcess create_model() called ==================================
2022-05-03 21:24:20,648:INFO:Initializing create_model()
2022-05-03 21:24:20,649:INFO:create_model(estimator=gbr, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:24:20,649:INFO:Checking exceptions
2022-05-03 21:24:20,649:INFO:Importing libraries
2022-05-03 21:24:20,650:INFO:Copying training dataset
2022-05-03 21:24:20,655:INFO:Defining folds
2022-05-03 21:24:20,656:INFO:Declaring metric variables
2022-05-03 21:24:20,684:INFO:Importing untrained model
2022-05-03 21:24:20,711:INFO:Gradient Boosting Regressor Imported succesfully
2022-05-03 21:24:20,762:INFO:Starting cross validation
2022-05-03 21:24:20,763:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:24:52,785:INFO:Calculating mean and std
2022-05-03 21:24:52,787:INFO:Creating metrics dataframe
2022-05-03 21:24:53,062:INFO:Uploading results into container
2022-05-03 21:24:53,062:INFO:Uploading model into container now
2022-05-03 21:24:53,063:INFO:create_model_container: 16
2022-05-03 21:24:53,063:INFO:master_model_container: 16
2022-05-03 21:24:53,064:INFO:display_container: 2
2022-05-03 21:24:53,066:INFO:GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                          init=None, learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='deprecated',
                          random_state=3515, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)
2022-05-03 21:24:53,066:INFO:create_model() succesfully completed......................................
2022-05-03 21:24:54,093:INFO:SubProcess create_model() end ==================================
2022-05-03 21:24:54,093:INFO:Creating metrics dataframe
2022-05-03 21:24:54,425:INFO:Initializing Light Gradient Boosting Machine
2022-05-03 21:24:54,426:INFO:Total runtime is 3.7602847377459208 minutes
2022-05-03 21:24:54,497:INFO:SubProcess create_model() called ==================================
2022-05-03 21:24:54,501:INFO:Initializing create_model()
2022-05-03 21:24:54,501:INFO:create_model(estimator=lightgbm, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:24:54,502:INFO:Checking exceptions
2022-05-03 21:24:54,502:INFO:Importing libraries
2022-05-03 21:24:54,502:INFO:Copying training dataset
2022-05-03 21:24:54,505:INFO:Defining folds
2022-05-03 21:24:54,506:INFO:Declaring metric variables
2022-05-03 21:24:54,550:INFO:Importing untrained model
2022-05-03 21:24:54,612:INFO:Light Gradient Boosting Machine Imported succesfully
2022-05-03 21:24:54,679:INFO:Starting cross validation
2022-05-03 21:24:54,706:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:25:02,744:INFO:Calculating mean and std
2022-05-03 21:25:02,759:INFO:Creating metrics dataframe
2022-05-03 21:25:02,940:INFO:Uploading results into container
2022-05-03 21:25:02,940:INFO:Uploading model into container now
2022-05-03 21:25:02,941:INFO:create_model_container: 17
2022-05-03 21:25:02,941:INFO:master_model_container: 17
2022-05-03 21:25:02,941:INFO:display_container: 2
2022-05-03 21:25:02,943:INFO:LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=3515, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
2022-05-03 21:25:02,943:INFO:create_model() succesfully completed......................................
2022-05-03 21:25:03,446:INFO:SubProcess create_model() end ==================================
2022-05-03 21:25:03,446:INFO:Creating metrics dataframe
2022-05-03 21:25:03,640:INFO:Initializing Dummy Regressor
2022-05-03 21:25:03,640:INFO:Total runtime is 3.9138683517773947 minutes
2022-05-03 21:25:03,677:INFO:SubProcess create_model() called ==================================
2022-05-03 21:25:03,678:INFO:Initializing create_model()
2022-05-03 21:25:03,678:INFO:create_model(estimator=dummy, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE6575A280>, kwargs={})
2022-05-03 21:25:03,679:INFO:Checking exceptions
2022-05-03 21:25:03,679:INFO:Importing libraries
2022-05-03 21:25:03,679:INFO:Copying training dataset
2022-05-03 21:25:03,685:INFO:Defining folds
2022-05-03 21:25:03,686:INFO:Declaring metric variables
2022-05-03 21:25:03,712:INFO:Importing untrained model
2022-05-03 21:25:03,782:INFO:Dummy Regressor Imported succesfully
2022-05-03 21:25:03,878:INFO:Starting cross validation
2022-05-03 21:25:03,880:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:25:04,560:INFO:Calculating mean and std
2022-05-03 21:25:04,562:INFO:Creating metrics dataframe
2022-05-03 21:25:04,722:INFO:Uploading results into container
2022-05-03 21:25:04,722:INFO:Uploading model into container now
2022-05-03 21:25:04,726:INFO:create_model_container: 18
2022-05-03 21:25:04,726:INFO:master_model_container: 18
2022-05-03 21:25:04,726:INFO:display_container: 2
2022-05-03 21:25:04,727:INFO:DummyRegressor(constant=None, quantile=None, strategy='mean')
2022-05-03 21:25:04,727:INFO:create_model() succesfully completed......................................
2022-05-03 21:25:05,532:INFO:SubProcess create_model() end ==================================
2022-05-03 21:25:05,533:INFO:Creating metrics dataframe
2022-05-03 21:25:05,749:INFO:Initializing create_model()
2022-05-03 21:25:05,750:INFO:create_model(estimator=LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=3515, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0), fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=None, kwargs={})
2022-05-03 21:25:05,751:INFO:Checking exceptions
2022-05-03 21:25:05,752:INFO:Importing libraries
2022-05-03 21:25:05,752:INFO:Copying training dataset
2022-05-03 21:25:05,754:INFO:Defining folds
2022-05-03 21:25:05,754:INFO:Declaring metric variables
2022-05-03 21:25:05,754:INFO:Importing untrained model
2022-05-03 21:25:05,755:INFO:Declaring custom model
2022-05-03 21:25:05,757:INFO:Light Gradient Boosting Machine Imported succesfully
2022-05-03 21:25:05,758:INFO:Cross validation set to False
2022-05-03 21:25:05,758:INFO:Fitting Model
2022-05-03 21:25:07,933:INFO:LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=3515, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
2022-05-03 21:25:07,934:INFO:create_models() succesfully completed......................................
2022-05-03 21:25:08,511:INFO:create_model_container: 18
2022-05-03 21:25:08,512:INFO:master_model_container: 18
2022-05-03 21:25:08,515:INFO:display_container: 2
2022-05-03 21:25:08,518:INFO:LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=3515, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
2022-05-03 21:25:08,518:INFO:compare_models() succesfully completed......................................
2022-05-03 21:25:37,898:INFO:Initializing predict_model()
2022-05-03 21:25:37,898:INFO:predict_model(estimator=LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=3515, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0), probability_threshold=None, encoded_labels=True, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.REGRESSION, display=None)
2022-05-03 21:25:37,899:INFO:Checking exceptions
2022-05-03 21:25:37,899:INFO:Preloading libraries
2022-05-03 21:25:37,899:INFO:Preparing display monitor
2022-05-03 21:28:34,368:INFO:PyCaret Supervised Module
2022-05-03 21:28:34,368:INFO:ML Usecase: regression
2022-05-03 21:28:34,368:INFO:version 2.3.6
2022-05-03 21:28:34,369:INFO:Initializing setup()
2022-05-03 21:28:34,369:INFO:setup(target=interest_rate, ml_usecase=regression, available_plots={'parameter': 'Hyperparameters', 'residuals': 'Residuals', 'error': 'Prediction Error', 'cooks': 'Cooks Distance', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'vc': 'Validation Curve', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'tree': 'Decision Tree', 'residuals_interactive': 'Interactive Residuals'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=kfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-05-03 21:28:34,369:INFO:Checking environment
2022-05-03 21:28:34,369:INFO:python_version: 3.8.12
2022-05-03 21:28:34,369:INFO:python_build: ('default', 'Oct 12 2021 03:01:40')
2022-05-03 21:28:34,369:INFO:machine: AMD64
2022-05-03 21:28:34,370:INFO:platform: Windows-10-10.0.19044-SP0
2022-05-03 21:28:34,372:WARNING:cannot find psutil installation. memory not traceable. Install psutil using pip to enable memory logging.
2022-05-03 21:28:34,372:INFO:Checking libraries
2022-05-03 21:28:34,372:INFO:pd==1.4.1
2022-05-03 21:28:34,373:INFO:numpy==1.19.5
2022-05-03 21:28:34,373:INFO:sklearn==0.23.2
2022-05-03 21:28:34,373:INFO:lightgbm==3.3.2
2022-05-03 21:28:34,375:WARNING:catboost not found
2022-05-03 21:28:34,377:WARNING:xgboost not found
2022-05-03 21:28:34,377:INFO:mlflow==1.24.0
2022-05-03 21:28:34,377:INFO:Checking Exceptions
2022-05-03 21:28:34,378:INFO:Declaring global variables
2022-05-03 21:28:34,378:INFO:USI: 089d
2022-05-03 21:28:34,378:INFO:pycaret_globals: {'_gpu_n_jobs_param', 'imputation_classifier', 'X_train', 'fix_imbalance_method_param', 'master_model_container', 'data_before_preprocess', 'html_param', 'y', '_all_metrics', 'exp_name_log', 'X_test', 'fold_generator', 'prep_pipe', 'y_test', 'logging_param', '_available_plots', 'target_param', 'seed', 'fold_groups_param_full', 'create_model_container', 'fold_groups_param', 'iterative_imputation_iters_param', 'experiment__', '_ml_usecase', 'fold_param', '_all_models_internal', 'USI', 'log_plots_param', '_all_models', 'n_jobs_param', 'pycaret_globals', 'imputation_regressor', 'display_container', 'fold_shuffle_param', 'stratify_param', 'transform_target_method_param', 'y_train', 'fix_imbalance_param', '_internal_pipeline', 'gpu_param', 'X', 'transform_target_param'}
2022-05-03 21:28:34,379:INFO:Preparing display monitor
2022-05-03 21:28:34,379:INFO:Preparing display monitor
2022-05-03 21:28:34,409:INFO:Importing libraries
2022-05-03 21:28:34,409:INFO:Copying data for preprocessing
2022-05-03 21:28:34,428:INFO:Declaring preprocessing parameters
2022-05-03 21:28:34,432:INFO:Creating preprocessing pipeline
2022-05-03 21:28:34,609:INFO:Preprocessing pipeline created successfully
2022-05-03 21:28:34,609:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-05-03 21:28:34,609:INFO:Creating global containers
2022-05-03 21:28:34,610:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2022-05-03 21:28:48,158:WARNING:Couldn't import xgboost.XGBRegressor
2022-05-03 21:28:48,160:WARNING:Couldn't import catboost.CatBoostRegressor
2022-05-03 21:28:48,566:WARNING:Couldn't import xgboost.XGBRegressor
2022-05-03 21:28:48,570:WARNING:Couldn't import catboost.CatBoostRegressor
2022-05-03 21:28:48,572:INFO:Creating grid variables
2022-05-03 21:28:48,603:INFO:create_model_container: 0
2022-05-03 21:28:48,607:INFO:master_model_container: 0
2022-05-03 21:28:48,607:INFO:display_container: 1
2022-05-03 21:28:48,617:INFO:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[], ml_usecase='regression',
                                      numerical_features=[],
                                      target='interest_rate',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_st...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='interest_rate')),
                ('fix_perfect', Remove_100(target='interest_rate')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)
2022-05-03 21:28:48,617:INFO:setup() succesfully completed......................................
2022-05-03 21:28:49,451:INFO:Initializing compare_models()
2022-05-03 21:28:49,451:INFO:compare_models(include=None, fold=None, round=4, cross_validation=True, sort=R2, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, probability_threshold=None, verbose=True, display=None, exclude=None)
2022-05-03 21:28:49,452:INFO:Checking exceptions
2022-05-03 21:28:49,452:INFO:Preparing display monitor
2022-05-03 21:28:49,452:INFO:Preparing display monitor
2022-05-03 21:28:49,517:INFO:Initializing Linear Regression
2022-05-03 21:28:49,517:INFO:Total runtime is 0.0 minutes
2022-05-03 21:28:49,566:INFO:SubProcess create_model() called ==================================
2022-05-03 21:28:49,567:INFO:Initializing create_model()
2022-05-03 21:28:49,567:INFO:create_model(estimator=lr, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:28:49,567:INFO:Checking exceptions
2022-05-03 21:28:49,567:INFO:Importing libraries
2022-05-03 21:28:49,568:INFO:Copying training dataset
2022-05-03 21:28:49,570:INFO:Defining folds
2022-05-03 21:28:49,571:INFO:Declaring metric variables
2022-05-03 21:28:49,608:INFO:Importing untrained model
2022-05-03 21:28:49,626:INFO:Linear Regression Imported succesfully
2022-05-03 21:28:49,669:INFO:Starting cross validation
2022-05-03 21:28:49,670:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:28:50,293:INFO:Calculating mean and std
2022-05-03 21:28:50,295:INFO:Creating metrics dataframe
2022-05-03 21:28:50,400:INFO:Uploading results into container
2022-05-03 21:28:50,400:INFO:Uploading model into container now
2022-05-03 21:28:50,400:INFO:create_model_container: 1
2022-05-03 21:28:50,400:INFO:master_model_container: 1
2022-05-03 21:28:50,400:INFO:display_container: 2
2022-05-03 21:28:50,401:INFO:LinearRegression(copy_X=True, fit_intercept=True, n_jobs=-1, normalize=False)
2022-05-03 21:28:50,401:INFO:create_model() succesfully completed......................................
2022-05-03 21:28:50,812:INFO:SubProcess create_model() end ==================================
2022-05-03 21:28:50,812:INFO:Creating metrics dataframe
2022-05-03 21:28:50,888:INFO:Initializing Lasso Regression
2022-05-03 21:28:50,889:INFO:Total runtime is 0.022870222727457683 minutes
2022-05-03 21:28:50,911:INFO:SubProcess create_model() called ==================================
2022-05-03 21:28:50,911:INFO:Initializing create_model()
2022-05-03 21:28:50,912:INFO:create_model(estimator=lasso, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:28:50,912:INFO:Checking exceptions
2022-05-03 21:28:50,912:INFO:Importing libraries
2022-05-03 21:28:50,912:INFO:Copying training dataset
2022-05-03 21:28:50,917:INFO:Defining folds
2022-05-03 21:28:50,919:INFO:Declaring metric variables
2022-05-03 21:28:50,944:INFO:Importing untrained model
2022-05-03 21:28:50,973:INFO:Lasso Regression Imported succesfully
2022-05-03 21:28:51,028:INFO:Starting cross validation
2022-05-03 21:28:51,031:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:28:51,547:INFO:Calculating mean and std
2022-05-03 21:28:51,551:INFO:Creating metrics dataframe
2022-05-03 21:28:51,653:INFO:Uploading results into container
2022-05-03 21:28:51,653:INFO:Uploading model into container now
2022-05-03 21:28:51,653:INFO:create_model_container: 2
2022-05-03 21:28:51,654:INFO:master_model_container: 2
2022-05-03 21:28:51,654:INFO:display_container: 2
2022-05-03 21:28:51,655:INFO:Lasso(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=8138,
      selection='cyclic', tol=0.0001, warm_start=False)
2022-05-03 21:28:51,655:INFO:create_model() succesfully completed......................................
2022-05-03 21:28:51,976:INFO:SubProcess create_model() end ==================================
2022-05-03 21:28:51,976:INFO:Creating metrics dataframe
2022-05-03 21:28:52,033:INFO:Initializing Ridge Regression
2022-05-03 21:28:52,033:INFO:Total runtime is 0.04192593097686768 minutes
2022-05-03 21:28:52,057:INFO:SubProcess create_model() called ==================================
2022-05-03 21:28:52,057:INFO:Initializing create_model()
2022-05-03 21:28:52,058:INFO:create_model(estimator=ridge, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:28:52,058:INFO:Checking exceptions
2022-05-03 21:28:52,058:INFO:Importing libraries
2022-05-03 21:28:52,058:INFO:Copying training dataset
2022-05-03 21:28:52,067:INFO:Defining folds
2022-05-03 21:28:52,067:INFO:Declaring metric variables
2022-05-03 21:28:52,110:INFO:Importing untrained model
2022-05-03 21:28:52,149:INFO:Ridge Regression Imported succesfully
2022-05-03 21:28:52,190:INFO:Starting cross validation
2022-05-03 21:28:52,191:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:28:52,764:INFO:Calculating mean and std
2022-05-03 21:28:52,767:INFO:Creating metrics dataframe
2022-05-03 21:28:52,885:INFO:Uploading results into container
2022-05-03 21:28:52,885:INFO:Uploading model into container now
2022-05-03 21:28:52,886:INFO:create_model_container: 3
2022-05-03 21:28:52,886:INFO:master_model_container: 3
2022-05-03 21:28:52,886:INFO:display_container: 2
2022-05-03 21:28:52,887:INFO:Ridge(alpha=1.0, copy_X=True, fit_intercept=True, max_iter=None,
      normalize=False, random_state=8138, solver='auto', tol=0.001)
2022-05-03 21:28:52,887:INFO:create_model() succesfully completed......................................
2022-05-03 21:28:53,202:INFO:SubProcess create_model() end ==================================
2022-05-03 21:28:53,203:INFO:Creating metrics dataframe
2022-05-03 21:28:53,267:INFO:Initializing Elastic Net
2022-05-03 21:28:53,267:INFO:Total runtime is 0.062497468789418545 minutes
2022-05-03 21:28:53,288:INFO:SubProcess create_model() called ==================================
2022-05-03 21:28:53,292:INFO:Initializing create_model()
2022-05-03 21:28:53,293:INFO:create_model(estimator=en, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:28:53,293:INFO:Checking exceptions
2022-05-03 21:28:53,293:INFO:Importing libraries
2022-05-03 21:28:53,293:INFO:Copying training dataset
2022-05-03 21:28:53,296:INFO:Defining folds
2022-05-03 21:28:53,298:INFO:Declaring metric variables
2022-05-03 21:28:53,320:INFO:Importing untrained model
2022-05-03 21:28:53,364:INFO:Elastic Net Imported succesfully
2022-05-03 21:28:53,400:INFO:Starting cross validation
2022-05-03 21:28:53,401:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:28:53,854:INFO:Calculating mean and std
2022-05-03 21:28:53,855:INFO:Creating metrics dataframe
2022-05-03 21:28:53,940:INFO:Uploading results into container
2022-05-03 21:28:53,941:INFO:Uploading model into container now
2022-05-03 21:28:53,941:INFO:create_model_container: 4
2022-05-03 21:28:53,941:INFO:master_model_container: 4
2022-05-03 21:28:53,941:INFO:display_container: 2
2022-05-03 21:28:53,942:INFO:ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
           max_iter=1000, normalize=False, positive=False, precompute=False,
           random_state=8138, selection='cyclic', tol=0.0001, warm_start=False)
2022-05-03 21:28:53,942:INFO:create_model() succesfully completed......................................
2022-05-03 21:28:54,241:INFO:SubProcess create_model() end ==================================
2022-05-03 21:28:54,241:INFO:Creating metrics dataframe
2022-05-03 21:28:54,299:INFO:Initializing Least Angle Regression
2022-05-03 21:28:54,299:INFO:Total runtime is 0.07970424493153891 minutes
2022-05-03 21:28:54,323:INFO:SubProcess create_model() called ==================================
2022-05-03 21:28:54,324:INFO:Initializing create_model()
2022-05-03 21:28:54,324:INFO:create_model(estimator=lar, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:28:54,324:INFO:Checking exceptions
2022-05-03 21:28:54,324:INFO:Importing libraries
2022-05-03 21:28:54,324:INFO:Copying training dataset
2022-05-03 21:28:54,326:INFO:Defining folds
2022-05-03 21:28:54,327:INFO:Declaring metric variables
2022-05-03 21:28:54,351:INFO:Importing untrained model
2022-05-03 21:28:54,371:INFO:Least Angle Regression Imported succesfully
2022-05-03 21:28:54,412:INFO:Starting cross validation
2022-05-03 21:28:54,414:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:28:54,928:INFO:Calculating mean and std
2022-05-03 21:28:54,933:INFO:Creating metrics dataframe
2022-05-03 21:28:55,023:INFO:Uploading results into container
2022-05-03 21:28:55,023:INFO:Uploading model into container now
2022-05-03 21:28:55,023:INFO:create_model_container: 5
2022-05-03 21:28:55,023:INFO:master_model_container: 5
2022-05-03 21:28:55,023:INFO:display_container: 2
2022-05-03 21:28:55,024:INFO:Lars(copy_X=True, eps=2.220446049250313e-16, fit_intercept=True, fit_path=True,
     jitter=None, n_nonzero_coefs=500, normalize=True, precompute='auto',
     random_state=8138, verbose=False)
2022-05-03 21:28:55,024:INFO:create_model() succesfully completed......................................
2022-05-03 21:28:55,313:INFO:SubProcess create_model() end ==================================
2022-05-03 21:28:55,313:INFO:Creating metrics dataframe
2022-05-03 21:28:55,397:INFO:Initializing Lasso Least Angle Regression
2022-05-03 21:28:55,398:INFO:Total runtime is 0.09801040887832643 minutes
2022-05-03 21:28:55,425:INFO:SubProcess create_model() called ==================================
2022-05-03 21:28:55,427:INFO:Initializing create_model()
2022-05-03 21:28:55,427:INFO:create_model(estimator=llar, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:28:55,427:INFO:Checking exceptions
2022-05-03 21:28:55,427:INFO:Importing libraries
2022-05-03 21:28:55,428:INFO:Copying training dataset
2022-05-03 21:28:55,430:INFO:Defining folds
2022-05-03 21:28:55,430:INFO:Declaring metric variables
2022-05-03 21:28:55,448:INFO:Importing untrained model
2022-05-03 21:28:55,464:INFO:Lasso Least Angle Regression Imported succesfully
2022-05-03 21:28:55,518:INFO:Starting cross validation
2022-05-03 21:28:55,520:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:28:55,806:INFO:Calculating mean and std
2022-05-03 21:28:55,808:INFO:Creating metrics dataframe
2022-05-03 21:28:55,895:INFO:Uploading results into container
2022-05-03 21:28:55,895:INFO:Uploading model into container now
2022-05-03 21:28:55,896:INFO:create_model_container: 6
2022-05-03 21:28:55,896:INFO:master_model_container: 6
2022-05-03 21:28:55,896:INFO:display_container: 2
2022-05-03 21:28:55,897:INFO:LassoLars(alpha=1.0, copy_X=True, eps=2.220446049250313e-16, fit_intercept=True,
          fit_path=True, jitter=None, max_iter=500, normalize=True,
          positive=False, precompute='auto', random_state=8138, verbose=False)
2022-05-03 21:28:55,897:INFO:create_model() succesfully completed......................................
2022-05-03 21:28:56,209:INFO:SubProcess create_model() end ==================================
2022-05-03 21:28:56,209:INFO:Creating metrics dataframe
2022-05-03 21:28:56,271:INFO:Initializing Orthogonal Matching Pursuit
2022-05-03 21:28:56,271:INFO:Total runtime is 0.1125687082608541 minutes
2022-05-03 21:28:56,292:INFO:SubProcess create_model() called ==================================
2022-05-03 21:28:56,294:INFO:Initializing create_model()
2022-05-03 21:28:56,294:INFO:create_model(estimator=omp, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:28:56,295:INFO:Checking exceptions
2022-05-03 21:28:56,295:INFO:Importing libraries
2022-05-03 21:28:56,295:INFO:Copying training dataset
2022-05-03 21:28:56,297:INFO:Defining folds
2022-05-03 21:28:56,297:INFO:Declaring metric variables
2022-05-03 21:28:56,316:INFO:Importing untrained model
2022-05-03 21:28:56,345:INFO:Orthogonal Matching Pursuit Imported succesfully
2022-05-03 21:28:56,385:INFO:Starting cross validation
2022-05-03 21:28:56,386:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:28:56,820:INFO:Calculating mean and std
2022-05-03 21:28:56,822:INFO:Creating metrics dataframe
2022-05-03 21:28:56,896:INFO:Uploading results into container
2022-05-03 21:28:56,897:INFO:Uploading model into container now
2022-05-03 21:28:56,897:INFO:create_model_container: 7
2022-05-03 21:28:56,897:INFO:master_model_container: 7
2022-05-03 21:28:56,897:INFO:display_container: 2
2022-05-03 21:28:56,898:INFO:OrthogonalMatchingPursuit(fit_intercept=True, n_nonzero_coefs=None,
                          normalize=True, precompute='auto', tol=None)
2022-05-03 21:28:56,898:INFO:create_model() succesfully completed......................................
2022-05-03 21:28:57,194:INFO:SubProcess create_model() end ==================================
2022-05-03 21:28:57,194:INFO:Creating metrics dataframe
2022-05-03 21:28:57,264:INFO:Initializing Bayesian Ridge
2022-05-03 21:28:57,264:INFO:Total runtime is 0.1291092117627462 minutes
2022-05-03 21:28:57,287:INFO:SubProcess create_model() called ==================================
2022-05-03 21:28:57,287:INFO:Initializing create_model()
2022-05-03 21:28:57,290:INFO:create_model(estimator=br, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:28:57,290:INFO:Checking exceptions
2022-05-03 21:28:57,290:INFO:Importing libraries
2022-05-03 21:28:57,290:INFO:Copying training dataset
2022-05-03 21:28:57,295:INFO:Defining folds
2022-05-03 21:28:57,296:INFO:Declaring metric variables
2022-05-03 21:28:57,313:INFO:Importing untrained model
2022-05-03 21:28:57,342:INFO:Bayesian Ridge Imported succesfully
2022-05-03 21:28:57,390:INFO:Starting cross validation
2022-05-03 21:28:57,391:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:28:58,243:INFO:Calculating mean and std
2022-05-03 21:28:58,245:INFO:Creating metrics dataframe
2022-05-03 21:28:58,338:INFO:Uploading results into container
2022-05-03 21:28:58,338:INFO:Uploading model into container now
2022-05-03 21:28:58,338:INFO:create_model_container: 8
2022-05-03 21:28:58,339:INFO:master_model_container: 8
2022-05-03 21:28:58,339:INFO:display_container: 2
2022-05-03 21:28:58,340:INFO:BayesianRidge(alpha_1=1e-06, alpha_2=1e-06, alpha_init=None,
              compute_score=False, copy_X=True, fit_intercept=True,
              lambda_1=1e-06, lambda_2=1e-06, lambda_init=None, n_iter=300,
              normalize=False, tol=0.001, verbose=False)
2022-05-03 21:28:58,340:INFO:create_model() succesfully completed......................................
2022-05-03 21:28:58,639:INFO:SubProcess create_model() end ==================================
2022-05-03 21:28:58,639:INFO:Creating metrics dataframe
2022-05-03 21:28:58,700:INFO:Initializing Passive Aggressive Regressor
2022-05-03 21:28:58,700:INFO:Total runtime is 0.15304548343022667 minutes
2022-05-03 21:28:58,740:INFO:SubProcess create_model() called ==================================
2022-05-03 21:28:58,741:INFO:Initializing create_model()
2022-05-03 21:28:58,741:INFO:create_model(estimator=par, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:28:58,741:INFO:Checking exceptions
2022-05-03 21:28:58,741:INFO:Importing libraries
2022-05-03 21:28:58,741:INFO:Copying training dataset
2022-05-03 21:28:58,744:INFO:Defining folds
2022-05-03 21:28:58,744:INFO:Declaring metric variables
2022-05-03 21:28:58,763:INFO:Importing untrained model
2022-05-03 21:28:58,787:INFO:Passive Aggressive Regressor Imported succesfully
2022-05-03 21:28:58,859:INFO:Starting cross validation
2022-05-03 21:28:58,860:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:29:00,087:INFO:Calculating mean and std
2022-05-03 21:29:00,089:INFO:Creating metrics dataframe
2022-05-03 21:29:00,173:INFO:Uploading results into container
2022-05-03 21:29:00,173:INFO:Uploading model into container now
2022-05-03 21:29:00,174:INFO:create_model_container: 9
2022-05-03 21:29:00,174:INFO:master_model_container: 9
2022-05-03 21:29:00,174:INFO:display_container: 2
2022-05-03 21:29:00,175:INFO:PassiveAggressiveRegressor(C=1.0, average=False, early_stopping=False,
                           epsilon=0.1, fit_intercept=True,
                           loss='epsilon_insensitive', max_iter=1000,
                           n_iter_no_change=5, random_state=8138, shuffle=True,
                           tol=0.001, validation_fraction=0.1, verbose=0,
                           warm_start=False)
2022-05-03 21:29:00,175:INFO:create_model() succesfully completed......................................
2022-05-03 21:29:00,474:INFO:SubProcess create_model() end ==================================
2022-05-03 21:29:00,474:INFO:Creating metrics dataframe
2022-05-03 21:29:00,553:INFO:Initializing Huber Regressor
2022-05-03 21:29:00,553:INFO:Total runtime is 0.18392776648203535 minutes
2022-05-03 21:29:00,574:INFO:SubProcess create_model() called ==================================
2022-05-03 21:29:00,575:INFO:Initializing create_model()
2022-05-03 21:29:00,575:INFO:create_model(estimator=huber, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:29:00,576:INFO:Checking exceptions
2022-05-03 21:29:00,576:INFO:Importing libraries
2022-05-03 21:29:00,576:INFO:Copying training dataset
2022-05-03 21:29:00,580:INFO:Defining folds
2022-05-03 21:29:00,583:INFO:Declaring metric variables
2022-05-03 21:29:00,606:INFO:Importing untrained model
2022-05-03 21:29:00,624:INFO:Huber Regressor Imported succesfully
2022-05-03 21:29:00,668:INFO:Starting cross validation
2022-05-03 21:29:00,669:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:29:09,137:INFO:Calculating mean and std
2022-05-03 21:29:09,140:INFO:Creating metrics dataframe
2022-05-03 21:29:09,237:INFO:Uploading results into container
2022-05-03 21:29:09,238:INFO:Uploading model into container now
2022-05-03 21:29:09,238:INFO:create_model_container: 10
2022-05-03 21:29:09,238:INFO:master_model_container: 10
2022-05-03 21:29:09,238:INFO:display_container: 2
2022-05-03 21:29:09,239:INFO:HuberRegressor(alpha=0.0001, epsilon=1.35, fit_intercept=True, max_iter=100,
               tol=1e-05, warm_start=False)
2022-05-03 21:29:09,239:INFO:create_model() succesfully completed......................................
2022-05-03 21:29:09,573:INFO:SubProcess create_model() end ==================================
2022-05-03 21:29:09,573:INFO:Creating metrics dataframe
2022-05-03 21:29:09,647:INFO:Initializing K Neighbors Regressor
2022-05-03 21:29:09,647:INFO:Total runtime is 0.3354907592137655 minutes
2022-05-03 21:29:09,669:INFO:SubProcess create_model() called ==================================
2022-05-03 21:29:09,669:INFO:Initializing create_model()
2022-05-03 21:29:09,670:INFO:create_model(estimator=knn, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:29:09,670:INFO:Checking exceptions
2022-05-03 21:29:09,670:INFO:Importing libraries
2022-05-03 21:29:09,670:INFO:Copying training dataset
2022-05-03 21:29:09,677:INFO:Defining folds
2022-05-03 21:29:09,677:INFO:Declaring metric variables
2022-05-03 21:29:09,703:INFO:Importing untrained model
2022-05-03 21:29:09,742:INFO:K Neighbors Regressor Imported succesfully
2022-05-03 21:29:09,794:INFO:Starting cross validation
2022-05-03 21:29:09,795:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:29:12,110:INFO:Calculating mean and std
2022-05-03 21:29:12,117:INFO:Creating metrics dataframe
2022-05-03 21:29:12,198:INFO:Uploading results into container
2022-05-03 21:29:12,198:INFO:Uploading model into container now
2022-05-03 21:29:12,198:INFO:create_model_container: 11
2022-05-03 21:29:12,199:INFO:master_model_container: 11
2022-05-03 21:29:12,199:INFO:display_container: 2
2022-05-03 21:29:12,199:INFO:KNeighborsRegressor(algorithm='auto', leaf_size=30, metric='minkowski',
                    metric_params=None, n_jobs=-1, n_neighbors=5, p=2,
                    weights='uniform')
2022-05-03 21:29:12,200:INFO:create_model() succesfully completed......................................
2022-05-03 21:29:12,520:INFO:SubProcess create_model() end ==================================
2022-05-03 21:29:12,520:INFO:Creating metrics dataframe
2022-05-03 21:29:12,586:INFO:Initializing Decision Tree Regressor
2022-05-03 21:29:12,587:INFO:Total runtime is 0.3844959656397502 minutes
2022-05-03 21:29:12,609:INFO:SubProcess create_model() called ==================================
2022-05-03 21:29:12,610:INFO:Initializing create_model()
2022-05-03 21:29:12,611:INFO:create_model(estimator=dt, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:29:12,611:INFO:Checking exceptions
2022-05-03 21:29:12,611:INFO:Importing libraries
2022-05-03 21:29:12,611:INFO:Copying training dataset
2022-05-03 21:29:12,614:INFO:Defining folds
2022-05-03 21:29:12,614:INFO:Declaring metric variables
2022-05-03 21:29:12,633:INFO:Importing untrained model
2022-05-03 21:29:12,655:INFO:Decision Tree Regressor Imported succesfully
2022-05-03 21:29:12,721:INFO:Starting cross validation
2022-05-03 21:29:12,722:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:29:13,970:INFO:Calculating mean and std
2022-05-03 21:29:13,973:INFO:Creating metrics dataframe
2022-05-03 21:29:14,070:INFO:Uploading results into container
2022-05-03 21:29:14,070:INFO:Uploading model into container now
2022-05-03 21:29:14,070:INFO:create_model_container: 12
2022-05-03 21:29:14,070:INFO:master_model_container: 12
2022-05-03 21:29:14,071:INFO:display_container: 2
2022-05-03 21:29:14,071:INFO:DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=8138, splitter='best')
2022-05-03 21:29:14,071:INFO:create_model() succesfully completed......................................
2022-05-03 21:29:14,373:INFO:SubProcess create_model() end ==================================
2022-05-03 21:29:14,373:INFO:Creating metrics dataframe
2022-05-03 21:29:14,437:INFO:Initializing Random Forest Regressor
2022-05-03 21:29:14,437:INFO:Total runtime is 0.4153282682100932 minutes
2022-05-03 21:29:14,458:INFO:SubProcess create_model() called ==================================
2022-05-03 21:29:14,461:INFO:Initializing create_model()
2022-05-03 21:29:14,461:INFO:create_model(estimator=rf, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:29:14,461:INFO:Checking exceptions
2022-05-03 21:29:14,462:INFO:Importing libraries
2022-05-03 21:29:14,462:INFO:Copying training dataset
2022-05-03 21:29:14,464:INFO:Defining folds
2022-05-03 21:29:14,464:INFO:Declaring metric variables
2022-05-03 21:29:14,484:INFO:Importing untrained model
2022-05-03 21:29:14,505:INFO:Random Forest Regressor Imported succesfully
2022-05-03 21:29:14,554:INFO:Starting cross validation
2022-05-03 21:29:14,555:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:29:44,770:INFO:Calculating mean and std
2022-05-03 21:29:44,773:INFO:Creating metrics dataframe
2022-05-03 21:29:44,859:INFO:Uploading results into container
2022-05-03 21:29:44,859:INFO:Uploading model into container now
2022-05-03 21:29:44,859:INFO:create_model_container: 13
2022-05-03 21:29:44,860:INFO:master_model_container: 13
2022-05-03 21:29:44,860:INFO:display_container: 2
2022-05-03 21:29:44,860:INFO:RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=100, n_jobs=-1, oob_score=False,
                      random_state=8138, verbose=0, warm_start=False)
2022-05-03 21:29:44,860:INFO:create_model() succesfully completed......................................
2022-05-03 21:29:45,163:INFO:SubProcess create_model() end ==================================
2022-05-03 21:29:45,165:INFO:Creating metrics dataframe
2022-05-03 21:29:45,234:INFO:Initializing Extra Trees Regressor
2022-05-03 21:29:45,235:INFO:Total runtime is 0.9286336024602255 minutes
2022-05-03 21:29:45,250:INFO:SubProcess create_model() called ==================================
2022-05-03 21:29:45,251:INFO:Initializing create_model()
2022-05-03 21:29:45,251:INFO:create_model(estimator=et, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:29:45,252:INFO:Checking exceptions
2022-05-03 21:29:45,253:INFO:Importing libraries
2022-05-03 21:29:45,253:INFO:Copying training dataset
2022-05-03 21:29:45,255:INFO:Defining folds
2022-05-03 21:29:45,255:INFO:Declaring metric variables
2022-05-03 21:29:45,277:INFO:Importing untrained model
2022-05-03 21:29:45,303:INFO:Extra Trees Regressor Imported succesfully
2022-05-03 21:29:45,341:INFO:Starting cross validation
2022-05-03 21:29:45,342:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:30:13,431:INFO:Calculating mean and std
2022-05-03 21:30:13,433:INFO:Creating metrics dataframe
2022-05-03 21:30:13,562:INFO:Uploading results into container
2022-05-03 21:30:13,562:INFO:Uploading model into container now
2022-05-03 21:30:13,562:INFO:create_model_container: 14
2022-05-03 21:30:13,563:INFO:master_model_container: 14
2022-05-03 21:30:13,564:INFO:display_container: 2
2022-05-03 21:30:13,565:INFO:ExtraTreesRegressor(bootstrap=False, ccp_alpha=0.0, criterion='mse',
                    max_depth=None, max_features='auto', max_leaf_nodes=None,
                    max_samples=None, min_impurity_decrease=0.0,
                    min_impurity_split=None, min_samples_leaf=1,
                    min_samples_split=2, min_weight_fraction_leaf=0.0,
                    n_estimators=100, n_jobs=-1, oob_score=False,
                    random_state=8138, verbose=0, warm_start=False)
2022-05-03 21:30:13,566:INFO:create_model() succesfully completed......................................
2022-05-03 21:30:13,975:INFO:SubProcess create_model() end ==================================
2022-05-03 21:30:13,975:INFO:Creating metrics dataframe
2022-05-03 21:30:14,080:INFO:Initializing AdaBoost Regressor
2022-05-03 21:30:14,081:INFO:Total runtime is 1.409390981992086 minutes
2022-05-03 21:30:14,106:INFO:SubProcess create_model() called ==================================
2022-05-03 21:30:14,107:INFO:Initializing create_model()
2022-05-03 21:30:14,125:INFO:create_model(estimator=ada, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:30:14,125:INFO:Checking exceptions
2022-05-03 21:30:14,125:INFO:Importing libraries
2022-05-03 21:30:14,126:INFO:Copying training dataset
2022-05-03 21:30:14,128:INFO:Defining folds
2022-05-03 21:30:14,128:INFO:Declaring metric variables
2022-05-03 21:30:14,149:INFO:Importing untrained model
2022-05-03 21:30:14,186:INFO:AdaBoost Regressor Imported succesfully
2022-05-03 21:30:14,259:INFO:Starting cross validation
2022-05-03 21:30:14,261:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:30:27,303:INFO:Calculating mean and std
2022-05-03 21:30:27,305:INFO:Creating metrics dataframe
2022-05-03 21:30:27,415:INFO:Uploading results into container
2022-05-03 21:30:27,415:INFO:Uploading model into container now
2022-05-03 21:30:27,416:INFO:create_model_container: 15
2022-05-03 21:30:27,416:INFO:master_model_container: 15
2022-05-03 21:30:27,416:INFO:display_container: 2
2022-05-03 21:30:27,417:INFO:AdaBoostRegressor(base_estimator=None, learning_rate=1.0, loss='linear',
                  n_estimators=50, random_state=8138)
2022-05-03 21:30:27,417:INFO:create_model() succesfully completed......................................
2022-05-03 21:30:27,794:INFO:SubProcess create_model() end ==================================
2022-05-03 21:30:27,794:INFO:Creating metrics dataframe
2022-05-03 21:30:27,885:INFO:Initializing Gradient Boosting Regressor
2022-05-03 21:30:27,885:INFO:Total runtime is 1.6394589106241864 minutes
2022-05-03 21:30:27,907:INFO:SubProcess create_model() called ==================================
2022-05-03 21:30:27,908:INFO:Initializing create_model()
2022-05-03 21:30:27,908:INFO:create_model(estimator=gbr, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:30:27,908:INFO:Checking exceptions
2022-05-03 21:30:27,909:INFO:Importing libraries
2022-05-03 21:30:27,909:INFO:Copying training dataset
2022-05-03 21:30:27,912:INFO:Defining folds
2022-05-03 21:30:27,912:INFO:Declaring metric variables
2022-05-03 21:30:27,943:INFO:Importing untrained model
2022-05-03 21:30:27,967:INFO:Gradient Boosting Regressor Imported succesfully
2022-05-03 21:30:28,013:INFO:Starting cross validation
2022-05-03 21:30:28,018:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:30:48,150:INFO:Calculating mean and std
2022-05-03 21:30:48,152:INFO:Creating metrics dataframe
2022-05-03 21:30:48,261:INFO:Uploading results into container
2022-05-03 21:30:48,261:INFO:Uploading model into container now
2022-05-03 21:30:48,261:INFO:create_model_container: 16
2022-05-03 21:30:48,262:INFO:master_model_container: 16
2022-05-03 21:30:48,262:INFO:display_container: 2
2022-05-03 21:30:48,263:INFO:GradientBoostingRegressor(alpha=0.9, ccp_alpha=0.0, criterion='friedman_mse',
                          init=None, learning_rate=0.1, loss='ls', max_depth=3,
                          max_features=None, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=100,
                          n_iter_no_change=None, presort='deprecated',
                          random_state=8138, subsample=1.0, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)
2022-05-03 21:30:48,263:INFO:create_model() succesfully completed......................................
2022-05-03 21:30:48,602:INFO:SubProcess create_model() end ==================================
2022-05-03 21:30:48,603:INFO:Creating metrics dataframe
2022-05-03 21:30:48,707:INFO:Initializing Light Gradient Boosting Machine
2022-05-03 21:30:48,709:INFO:Total runtime is 1.9865263700485232 minutes
2022-05-03 21:30:48,732:INFO:SubProcess create_model() called ==================================
2022-05-03 21:30:48,733:INFO:Initializing create_model()
2022-05-03 21:30:48,733:INFO:create_model(estimator=lightgbm, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:30:48,734:INFO:Checking exceptions
2022-05-03 21:30:48,734:INFO:Importing libraries
2022-05-03 21:30:48,734:INFO:Copying training dataset
2022-05-03 21:30:48,737:INFO:Defining folds
2022-05-03 21:30:48,739:INFO:Declaring metric variables
2022-05-03 21:30:48,762:INFO:Importing untrained model
2022-05-03 21:30:48,784:INFO:Light Gradient Boosting Machine Imported succesfully
2022-05-03 21:30:48,833:INFO:Starting cross validation
2022-05-03 21:30:48,834:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:30:52,048:INFO:Calculating mean and std
2022-05-03 21:30:52,049:INFO:Creating metrics dataframe
2022-05-03 21:30:52,144:INFO:Uploading results into container
2022-05-03 21:30:52,145:INFO:Uploading model into container now
2022-05-03 21:30:52,145:INFO:create_model_container: 17
2022-05-03 21:30:52,145:INFO:master_model_container: 17
2022-05-03 21:30:52,145:INFO:display_container: 2
2022-05-03 21:30:52,146:INFO:LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=8138, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
2022-05-03 21:30:52,146:INFO:create_model() succesfully completed......................................
2022-05-03 21:30:52,457:INFO:SubProcess create_model() end ==================================
2022-05-03 21:30:52,457:INFO:Creating metrics dataframe
2022-05-03 21:30:52,550:INFO:Initializing Dummy Regressor
2022-05-03 21:30:52,550:INFO:Total runtime is 2.050539600849152 minutes
2022-05-03 21:30:52,570:INFO:SubProcess create_model() called ==================================
2022-05-03 21:30:52,571:INFO:Initializing create_model()
2022-05-03 21:30:52,572:INFO:create_model(estimator=dummy, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE30AB17C0>, kwargs={})
2022-05-03 21:30:52,572:INFO:Checking exceptions
2022-05-03 21:30:52,572:INFO:Importing libraries
2022-05-03 21:30:52,572:INFO:Copying training dataset
2022-05-03 21:30:52,574:INFO:Defining folds
2022-05-03 21:30:52,575:INFO:Declaring metric variables
2022-05-03 21:30:52,597:INFO:Importing untrained model
2022-05-03 21:30:52,643:INFO:Dummy Regressor Imported succesfully
2022-05-03 21:30:52,701:INFO:Starting cross validation
2022-05-03 21:30:52,702:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 21:30:53,029:INFO:Calculating mean and std
2022-05-03 21:30:53,033:INFO:Creating metrics dataframe
2022-05-03 21:30:53,200:INFO:Uploading results into container
2022-05-03 21:30:53,201:INFO:Uploading model into container now
2022-05-03 21:30:53,217:INFO:create_model_container: 18
2022-05-03 21:30:53,218:INFO:master_model_container: 18
2022-05-03 21:30:53,218:INFO:display_container: 2
2022-05-03 21:30:53,219:INFO:DummyRegressor(constant=None, quantile=None, strategy='mean')
2022-05-03 21:30:53,220:INFO:create_model() succesfully completed......................................
2022-05-03 21:30:53,626:INFO:SubProcess create_model() end ==================================
2022-05-03 21:30:53,626:INFO:Creating metrics dataframe
2022-05-03 21:30:53,790:INFO:Initializing create_model()
2022-05-03 21:30:53,791:INFO:create_model(estimator=LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=8138, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0), fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=False, predict=False, fit_kwargs={}, groups=None, refit=True, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=None, kwargs={})
2022-05-03 21:30:53,791:INFO:Checking exceptions
2022-05-03 21:30:53,791:INFO:Importing libraries
2022-05-03 21:30:53,792:INFO:Copying training dataset
2022-05-03 21:30:53,793:INFO:Defining folds
2022-05-03 21:30:53,794:INFO:Declaring metric variables
2022-05-03 21:30:53,794:INFO:Importing untrained model
2022-05-03 21:30:53,794:INFO:Declaring custom model
2022-05-03 21:30:53,796:INFO:Light Gradient Boosting Machine Imported succesfully
2022-05-03 21:30:53,797:INFO:Cross validation set to False
2022-05-03 21:30:53,797:INFO:Fitting Model
2022-05-03 21:30:54,630:INFO:LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=8138, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
2022-05-03 21:30:54,630:INFO:create_models() succesfully completed......................................
2022-05-03 21:30:55,081:INFO:create_model_container: 18
2022-05-03 21:30:55,081:INFO:master_model_container: 18
2022-05-03 21:30:55,081:INFO:display_container: 2
2022-05-03 21:30:55,083:INFO:LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=8138, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0)
2022-05-03 21:30:55,083:INFO:compare_models() succesfully completed......................................
2022-05-03 21:30:55,691:INFO:Initializing predict_model()
2022-05-03 21:30:55,692:INFO:predict_model(estimator=LGBMRegressor(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
              importance_type='split', learning_rate=0.1, max_depth=-1,
              min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
              n_estimators=100, n_jobs=-1, num_leaves=31, objective=None,
              random_state=8138, reg_alpha=0.0, reg_lambda=0.0, silent='warn',
              subsample=1.0, subsample_for_bin=200000, subsample_freq=0), probability_threshold=None, encoded_labels=True, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.REGRESSION, display=None)
2022-05-03 21:30:55,692:INFO:Checking exceptions
2022-05-03 21:30:55,692:INFO:Preloading libraries
2022-05-03 21:30:55,692:INFO:Preparing display monitor
2022-05-03 23:52:16,339:INFO:PyCaret Supervised Module
2022-05-03 23:52:16,346:INFO:ML Usecase: regression
2022-05-03 23:52:16,346:INFO:version 2.3.6
2022-05-03 23:52:16,346:INFO:Initializing setup()
2022-05-03 23:52:16,348:INFO:setup(target=interest_rate, ml_usecase=regression, available_plots={'parameter': 'Hyperparameters', 'residuals': 'Residuals', 'error': 'Prediction Error', 'cooks': 'Cooks Distance', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'vc': 'Validation Curve', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'tree': 'Decision Tree', 'residuals_interactive': 'Interactive Residuals'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=kfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-05-03 23:52:16,348:INFO:Checking environment
2022-05-03 23:52:16,348:INFO:python_version: 3.8.12
2022-05-03 23:52:16,349:INFO:python_build: ('default', 'Oct 12 2021 03:01:40')
2022-05-03 23:52:16,350:INFO:machine: AMD64
2022-05-03 23:52:16,351:INFO:platform: Windows-10-10.0.19044-SP0
2022-05-03 23:52:16,376:WARNING:cannot find psutil installation. memory not traceable. Install psutil using pip to enable memory logging.
2022-05-03 23:52:16,376:INFO:Checking libraries
2022-05-03 23:52:16,376:INFO:pd==1.4.1
2022-05-03 23:52:16,376:INFO:numpy==1.19.5
2022-05-03 23:52:16,376:INFO:sklearn==0.23.2
2022-05-03 23:52:16,380:INFO:lightgbm==3.3.2
2022-05-03 23:52:16,383:WARNING:catboost not found
2022-05-03 23:52:16,385:WARNING:xgboost not found
2022-05-03 23:52:16,385:INFO:mlflow==1.24.0
2022-05-03 23:52:16,385:INFO:Checking Exceptions
2022-05-03 23:52:16,389:INFO:Declaring global variables
2022-05-03 23:52:16,389:INFO:USI: bf9b
2022-05-03 23:52:16,390:INFO:pycaret_globals: {'_gpu_n_jobs_param', 'imputation_classifier', 'X_train', 'fix_imbalance_method_param', 'master_model_container', 'data_before_preprocess', 'html_param', 'y', '_all_metrics', 'exp_name_log', 'X_test', 'fold_generator', 'prep_pipe', 'y_test', 'logging_param', '_available_plots', 'target_param', 'seed', 'fold_groups_param_full', 'create_model_container', 'fold_groups_param', 'iterative_imputation_iters_param', 'experiment__', '_ml_usecase', 'fold_param', '_all_models_internal', 'USI', 'log_plots_param', '_all_models', 'n_jobs_param', 'pycaret_globals', 'imputation_regressor', 'display_container', 'fold_shuffle_param', 'stratify_param', 'transform_target_method_param', 'y_train', 'fix_imbalance_param', '_internal_pipeline', 'gpu_param', 'X', 'transform_target_param'}
2022-05-03 23:52:16,390:INFO:Preparing display monitor
2022-05-03 23:52:16,393:INFO:Preparing display monitor
2022-05-03 23:52:16,466:INFO:Importing libraries
2022-05-03 23:52:16,467:INFO:Copying data for preprocessing
2022-05-03 23:52:16,488:INFO:Declaring preprocessing parameters
2022-05-03 23:52:16,492:INFO:Creating preprocessing pipeline
2022-05-03 23:52:16,617:INFO:Preprocessing pipeline created successfully
2022-05-03 23:52:16,618:ERROR:(Process Exit): setup has been interupted with user command 'quit'. setup must rerun.
2022-05-03 23:52:16,618:INFO:Creating global containers
2022-05-03 23:52:16,626:INFO:Internal pipeline: Pipeline(memory=None, steps=[('empty_step', 'passthrough')], verbose=False)
2022-05-03 23:52:21,741:WARNING:Couldn't import xgboost.XGBRegressor
2022-05-03 23:52:21,742:WARNING:Couldn't import catboost.CatBoostRegressor
2022-05-03 23:52:22,157:WARNING:Couldn't import xgboost.XGBRegressor
2022-05-03 23:52:22,160:WARNING:Couldn't import catboost.CatBoostRegressor
2022-05-03 23:52:22,161:INFO:Creating grid variables
2022-05-03 23:52:22,193:INFO:create_model_container: 0
2022-05-03 23:52:22,194:INFO:master_model_container: 0
2022-05-03 23:52:22,194:INFO:display_container: 1
2022-05-03 23:52:22,207:INFO:Pipeline(memory=None,
         steps=[('dtypes',
                 DataTypes_Auto_infer(categorical_features=[],
                                      display_types=True, features_todrop=[],
                                      id_columns=[], ml_usecase='regression',
                                      numerical_features=[],
                                      target='interest_rate',
                                      time_features=[])),
                ('imputer',
                 Simple_Imputer(categorical_strategy='not_available',
                                fill_value_categorical=None,
                                fill_value_numerical=None,
                                numeric_st...
                ('scaling', 'passthrough'), ('P_transform', 'passthrough'),
                ('binn', 'passthrough'), ('rem_outliers', 'passthrough'),
                ('cluster_all', 'passthrough'),
                ('dummy', Dummify(target='interest_rate')),
                ('fix_perfect', Remove_100(target='interest_rate')),
                ('clean_names', Clean_Colum_Names()),
                ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                ('dfs', 'passthrough'), ('pca', 'passthrough')],
         verbose=False)
2022-05-03 23:52:22,207:INFO:setup() succesfully completed......................................
2022-05-03 23:52:23,619:INFO:Initializing compare_models()
2022-05-03 23:52:23,619:INFO:compare_models(include=None, fold=None, round=4, cross_validation=True, sort=R2, n_select=1, budget_time=None, turbo=True, errors=ignore, fit_kwargs=None, groups=None, probability_threshold=None, verbose=True, display=None, exclude=None)
2022-05-03 23:52:23,620:INFO:Checking exceptions
2022-05-03 23:52:23,620:INFO:Preparing display monitor
2022-05-03 23:52:23,620:INFO:Preparing display monitor
2022-05-03 23:52:23,675:INFO:Initializing Linear Regression
2022-05-03 23:52:23,675:INFO:Total runtime is 0.0 minutes
2022-05-03 23:52:23,693:INFO:SubProcess create_model() called ==================================
2022-05-03 23:52:23,693:INFO:Initializing create_model()
2022-05-03 23:52:23,694:INFO:create_model(estimator=lr, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:23,694:INFO:Checking exceptions
2022-05-03 23:52:23,694:INFO:Importing libraries
2022-05-03 23:52:23,694:INFO:Copying training dataset
2022-05-03 23:52:23,696:INFO:Defining folds
2022-05-03 23:52:23,696:INFO:Declaring metric variables
2022-05-03 23:52:23,711:INFO:Importing untrained model
2022-05-03 23:52:23,727:INFO:Linear Regression Imported succesfully
2022-05-03 23:52:23,763:INFO:Starting cross validation
2022-05-03 23:52:23,765:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:32,344:WARNING:create_model() for lr raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:52:32,358:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:32,359:INFO:Initializing create_model()
2022-05-03 23:52:32,359:INFO:create_model(estimator=lr, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:32,359:INFO:Checking exceptions
2022-05-03 23:52:32,360:INFO:Importing libraries
2022-05-03 23:52:32,360:INFO:Copying training dataset
2022-05-03 23:52:32,363:INFO:Defining folds
2022-05-03 23:52:32,363:INFO:Declaring metric variables
2022-05-03 23:52:32,384:INFO:Importing untrained model
2022-05-03 23:52:32,401:INFO:Linear Regression Imported succesfully
2022-05-03 23:52:32,439:INFO:Starting cross validation
2022-05-03 23:52:32,441:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:32,659:ERROR:create_model() for lr raised an exception or returned all 0.0:
2022-05-03 23:52:32,661:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:32,663:INFO:Initializing Lasso Regression
2022-05-03 23:52:32,663:INFO:Total runtime is 0.14980081717173258 minutes
2022-05-03 23:52:32,698:INFO:SubProcess create_model() called ==================================
2022-05-03 23:52:32,699:INFO:Initializing create_model()
2022-05-03 23:52:32,699:INFO:create_model(estimator=lasso, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:32,700:INFO:Checking exceptions
2022-05-03 23:52:32,701:INFO:Importing libraries
2022-05-03 23:52:32,701:INFO:Copying training dataset
2022-05-03 23:52:32,706:INFO:Defining folds
2022-05-03 23:52:32,706:INFO:Declaring metric variables
2022-05-03 23:52:32,726:INFO:Importing untrained model
2022-05-03 23:52:32,754:INFO:Lasso Regression Imported succesfully
2022-05-03 23:52:32,790:INFO:Starting cross validation
2022-05-03 23:52:32,791:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:33,126:WARNING:create_model() for lasso raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:52:33,128:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:33,128:INFO:Initializing create_model()
2022-05-03 23:52:33,128:INFO:create_model(estimator=lasso, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:33,128:INFO:Checking exceptions
2022-05-03 23:52:33,128:INFO:Importing libraries
2022-05-03 23:52:33,128:INFO:Copying training dataset
2022-05-03 23:52:33,153:INFO:Defining folds
2022-05-03 23:52:33,154:INFO:Declaring metric variables
2022-05-03 23:52:33,186:INFO:Importing untrained model
2022-05-03 23:52:33,204:INFO:Lasso Regression Imported succesfully
2022-05-03 23:52:33,244:INFO:Starting cross validation
2022-05-03 23:52:33,245:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:33,631:ERROR:create_model() for lasso raised an exception or returned all 0.0:
2022-05-03 23:52:33,635:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:33,641:INFO:Initializing Ridge Regression
2022-05-03 23:52:33,642:INFO:Total runtime is 0.1661020000775655 minutes
2022-05-03 23:52:33,673:INFO:SubProcess create_model() called ==================================
2022-05-03 23:52:33,673:INFO:Initializing create_model()
2022-05-03 23:52:33,674:INFO:create_model(estimator=ridge, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:33,674:INFO:Checking exceptions
2022-05-03 23:52:33,674:INFO:Importing libraries
2022-05-03 23:52:33,674:INFO:Copying training dataset
2022-05-03 23:52:33,678:INFO:Defining folds
2022-05-03 23:52:33,678:INFO:Declaring metric variables
2022-05-03 23:52:33,689:INFO:Importing untrained model
2022-05-03 23:52:33,706:INFO:Ridge Regression Imported succesfully
2022-05-03 23:52:33,735:INFO:Starting cross validation
2022-05-03 23:52:33,736:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:33,978:WARNING:create_model() for ridge raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:52:33,980:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:33,981:INFO:Initializing create_model()
2022-05-03 23:52:33,981:INFO:create_model(estimator=ridge, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:33,981:INFO:Checking exceptions
2022-05-03 23:52:33,982:INFO:Importing libraries
2022-05-03 23:52:33,982:INFO:Copying training dataset
2022-05-03 23:52:33,989:INFO:Defining folds
2022-05-03 23:52:33,990:INFO:Declaring metric variables
2022-05-03 23:52:34,034:INFO:Importing untrained model
2022-05-03 23:52:34,065:INFO:Ridge Regression Imported succesfully
2022-05-03 23:52:34,101:INFO:Starting cross validation
2022-05-03 23:52:34,103:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:34,226:ERROR:create_model() for ridge raised an exception or returned all 0.0:
2022-05-03 23:52:34,227:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:34,227:INFO:Initializing Elastic Net
2022-05-03 23:52:34,227:INFO:Total runtime is 0.1758693257967631 minutes
2022-05-03 23:52:34,240:INFO:SubProcess create_model() called ==================================
2022-05-03 23:52:34,241:INFO:Initializing create_model()
2022-05-03 23:52:34,241:INFO:create_model(estimator=en, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:34,241:INFO:Checking exceptions
2022-05-03 23:52:34,242:INFO:Importing libraries
2022-05-03 23:52:34,242:INFO:Copying training dataset
2022-05-03 23:52:34,244:INFO:Defining folds
2022-05-03 23:52:34,244:INFO:Declaring metric variables
2022-05-03 23:52:34,256:INFO:Importing untrained model
2022-05-03 23:52:34,269:INFO:Elastic Net Imported succesfully
2022-05-03 23:52:34,308:INFO:Starting cross validation
2022-05-03 23:52:34,309:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:34,591:WARNING:create_model() for en raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:52:34,592:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:34,592:INFO:Initializing create_model()
2022-05-03 23:52:34,592:INFO:create_model(estimator=en, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:34,592:INFO:Checking exceptions
2022-05-03 23:52:34,592:INFO:Importing libraries
2022-05-03 23:52:34,592:INFO:Copying training dataset
2022-05-03 23:52:34,594:INFO:Defining folds
2022-05-03 23:52:34,594:INFO:Declaring metric variables
2022-05-03 23:52:34,604:INFO:Importing untrained model
2022-05-03 23:52:34,619:INFO:Elastic Net Imported succesfully
2022-05-03 23:52:34,649:INFO:Starting cross validation
2022-05-03 23:52:34,651:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:35,103:ERROR:create_model() for en raised an exception or returned all 0.0:
2022-05-03 23:52:35,109:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:35,110:INFO:Initializing Least Angle Regression
2022-05-03 23:52:35,111:INFO:Total runtime is 0.19060101509094238 minutes
2022-05-03 23:52:35,143:INFO:SubProcess create_model() called ==================================
2022-05-03 23:52:35,144:INFO:Initializing create_model()
2022-05-03 23:52:35,144:INFO:create_model(estimator=lar, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:35,144:INFO:Checking exceptions
2022-05-03 23:52:35,148:INFO:Importing libraries
2022-05-03 23:52:35,148:INFO:Copying training dataset
2022-05-03 23:52:35,153:INFO:Defining folds
2022-05-03 23:52:35,154:INFO:Declaring metric variables
2022-05-03 23:52:35,171:INFO:Importing untrained model
2022-05-03 23:52:35,191:INFO:Least Angle Regression Imported succesfully
2022-05-03 23:52:35,227:INFO:Starting cross validation
2022-05-03 23:52:35,228:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:35,633:WARNING:create_model() for lar raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:52:35,635:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:35,636:INFO:Initializing create_model()
2022-05-03 23:52:35,636:INFO:create_model(estimator=lar, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:35,637:INFO:Checking exceptions
2022-05-03 23:52:35,637:INFO:Importing libraries
2022-05-03 23:52:35,637:INFO:Copying training dataset
2022-05-03 23:52:35,644:INFO:Defining folds
2022-05-03 23:52:35,645:INFO:Declaring metric variables
2022-05-03 23:52:35,686:INFO:Importing untrained model
2022-05-03 23:52:35,704:INFO:Least Angle Regression Imported succesfully
2022-05-03 23:52:35,730:INFO:Starting cross validation
2022-05-03 23:52:35,732:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:36,240:ERROR:create_model() for lar raised an exception or returned all 0.0:
2022-05-03 23:52:36,242:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:36,243:INFO:Initializing Lasso Least Angle Regression
2022-05-03 23:52:36,243:INFO:Total runtime is 0.20947096347808838 minutes
2022-05-03 23:52:36,262:INFO:SubProcess create_model() called ==================================
2022-05-03 23:52:36,262:INFO:Initializing create_model()
2022-05-03 23:52:36,263:INFO:create_model(estimator=llar, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:36,263:INFO:Checking exceptions
2022-05-03 23:52:36,264:INFO:Importing libraries
2022-05-03 23:52:36,264:INFO:Copying training dataset
2022-05-03 23:52:36,267:INFO:Defining folds
2022-05-03 23:52:36,267:INFO:Declaring metric variables
2022-05-03 23:52:36,282:INFO:Importing untrained model
2022-05-03 23:52:36,299:INFO:Lasso Least Angle Regression Imported succesfully
2022-05-03 23:52:36,350:INFO:Starting cross validation
2022-05-03 23:52:36,351:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:36,745:WARNING:create_model() for llar raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:52:36,748:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:36,749:INFO:Initializing create_model()
2022-05-03 23:52:36,749:INFO:create_model(estimator=llar, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:36,749:INFO:Checking exceptions
2022-05-03 23:52:36,749:INFO:Importing libraries
2022-05-03 23:52:36,749:INFO:Copying training dataset
2022-05-03 23:52:36,750:INFO:Defining folds
2022-05-03 23:52:36,751:INFO:Declaring metric variables
2022-05-03 23:52:36,760:INFO:Importing untrained model
2022-05-03 23:52:36,775:INFO:Lasso Least Angle Regression Imported succesfully
2022-05-03 23:52:36,805:INFO:Starting cross validation
2022-05-03 23:52:36,807:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:37,091:ERROR:create_model() for llar raised an exception or returned all 0.0:
2022-05-03 23:52:37,104:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:37,106:INFO:Initializing Orthogonal Matching Pursuit
2022-05-03 23:52:37,107:INFO:Total runtime is 0.22386234203974406 minutes
2022-05-03 23:52:37,143:INFO:SubProcess create_model() called ==================================
2022-05-03 23:52:37,144:INFO:Initializing create_model()
2022-05-03 23:52:37,144:INFO:create_model(estimator=omp, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:37,144:INFO:Checking exceptions
2022-05-03 23:52:37,144:INFO:Importing libraries
2022-05-03 23:52:37,144:INFO:Copying training dataset
2022-05-03 23:52:37,146:INFO:Defining folds
2022-05-03 23:52:37,148:INFO:Declaring metric variables
2022-05-03 23:52:37,157:INFO:Importing untrained model
2022-05-03 23:52:37,171:INFO:Orthogonal Matching Pursuit Imported succesfully
2022-05-03 23:52:37,202:INFO:Starting cross validation
2022-05-03 23:52:37,203:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:37,681:WARNING:create_model() for omp raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:52:37,682:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:37,683:INFO:Initializing create_model()
2022-05-03 23:52:37,683:INFO:create_model(estimator=omp, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:37,683:INFO:Checking exceptions
2022-05-03 23:52:37,683:INFO:Importing libraries
2022-05-03 23:52:37,683:INFO:Copying training dataset
2022-05-03 23:52:37,684:INFO:Defining folds
2022-05-03 23:52:37,685:INFO:Declaring metric variables
2022-05-03 23:52:37,693:INFO:Importing untrained model
2022-05-03 23:52:37,707:INFO:Orthogonal Matching Pursuit Imported succesfully
2022-05-03 23:52:37,745:INFO:Starting cross validation
2022-05-03 23:52:37,746:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:38,061:ERROR:create_model() for omp raised an exception or returned all 0.0:
2022-05-03 23:52:38,065:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:38,072:INFO:Initializing Bayesian Ridge
2022-05-03 23:52:38,072:INFO:Total runtime is 0.23994505405426025 minutes
2022-05-03 23:52:38,128:INFO:SubProcess create_model() called ==================================
2022-05-03 23:52:38,128:INFO:Initializing create_model()
2022-05-03 23:52:38,128:INFO:create_model(estimator=br, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:38,129:INFO:Checking exceptions
2022-05-03 23:52:38,129:INFO:Importing libraries
2022-05-03 23:52:38,129:INFO:Copying training dataset
2022-05-03 23:52:38,131:INFO:Defining folds
2022-05-03 23:52:38,132:INFO:Declaring metric variables
2022-05-03 23:52:38,153:INFO:Importing untrained model
2022-05-03 23:52:38,172:INFO:Bayesian Ridge Imported succesfully
2022-05-03 23:52:38,220:INFO:Starting cross validation
2022-05-03 23:52:38,222:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:38,925:WARNING:create_model() for br raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:52:38,927:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:38,928:INFO:Initializing create_model()
2022-05-03 23:52:38,928:INFO:create_model(estimator=br, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:38,928:INFO:Checking exceptions
2022-05-03 23:52:38,928:INFO:Importing libraries
2022-05-03 23:52:38,928:INFO:Copying training dataset
2022-05-03 23:52:38,930:INFO:Defining folds
2022-05-03 23:52:38,930:INFO:Declaring metric variables
2022-05-03 23:52:38,945:INFO:Importing untrained model
2022-05-03 23:52:38,966:INFO:Bayesian Ridge Imported succesfully
2022-05-03 23:52:39,012:INFO:Starting cross validation
2022-05-03 23:52:39,013:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:39,458:ERROR:create_model() for br raised an exception or returned all 0.0:
2022-05-03 23:52:39,459:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:39,459:INFO:Initializing Passive Aggressive Regressor
2022-05-03 23:52:39,459:INFO:Total runtime is 0.26305870215098065 minutes
2022-05-03 23:52:39,469:INFO:SubProcess create_model() called ==================================
2022-05-03 23:52:39,472:INFO:Initializing create_model()
2022-05-03 23:52:39,472:INFO:create_model(estimator=par, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:39,472:INFO:Checking exceptions
2022-05-03 23:52:39,472:INFO:Importing libraries
2022-05-03 23:52:39,472:INFO:Copying training dataset
2022-05-03 23:52:39,475:INFO:Defining folds
2022-05-03 23:52:39,475:INFO:Declaring metric variables
2022-05-03 23:52:39,486:INFO:Importing untrained model
2022-05-03 23:52:39,501:INFO:Passive Aggressive Regressor Imported succesfully
2022-05-03 23:52:39,531:INFO:Starting cross validation
2022-05-03 23:52:39,532:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:40,402:WARNING:create_model() for par raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:52:40,407:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:40,409:INFO:Initializing create_model()
2022-05-03 23:52:40,409:INFO:create_model(estimator=par, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:40,409:INFO:Checking exceptions
2022-05-03 23:52:40,410:INFO:Importing libraries
2022-05-03 23:52:40,410:INFO:Copying training dataset
2022-05-03 23:52:40,414:INFO:Defining folds
2022-05-03 23:52:40,416:INFO:Declaring metric variables
2022-05-03 23:52:40,466:INFO:Importing untrained model
2022-05-03 23:52:40,491:INFO:Passive Aggressive Regressor Imported succesfully
2022-05-03 23:52:40,529:INFO:Starting cross validation
2022-05-03 23:52:40,532:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:41,811:ERROR:create_model() for par raised an exception or returned all 0.0:
2022-05-03 23:52:41,812:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:41,813:INFO:Initializing Huber Regressor
2022-05-03 23:52:41,813:INFO:Total runtime is 0.30229190985361737 minutes
2022-05-03 23:52:41,834:INFO:SubProcess create_model() called ==================================
2022-05-03 23:52:41,835:INFO:Initializing create_model()
2022-05-03 23:52:41,836:INFO:create_model(estimator=huber, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:41,837:INFO:Checking exceptions
2022-05-03 23:52:41,837:INFO:Importing libraries
2022-05-03 23:52:41,837:INFO:Copying training dataset
2022-05-03 23:52:41,840:INFO:Defining folds
2022-05-03 23:52:41,840:INFO:Declaring metric variables
2022-05-03 23:52:41,861:INFO:Importing untrained model
2022-05-03 23:52:41,882:INFO:Huber Regressor Imported succesfully
2022-05-03 23:52:41,919:INFO:Starting cross validation
2022-05-03 23:52:41,920:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:48,546:WARNING:create_model() for huber raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:52:48,551:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:48,552:INFO:Initializing create_model()
2022-05-03 23:52:48,552:INFO:create_model(estimator=huber, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:48,552:INFO:Checking exceptions
2022-05-03 23:52:48,553:INFO:Importing libraries
2022-05-03 23:52:48,553:INFO:Copying training dataset
2022-05-03 23:52:48,558:INFO:Defining folds
2022-05-03 23:52:48,563:INFO:Declaring metric variables
2022-05-03 23:52:48,597:INFO:Importing untrained model
2022-05-03 23:52:48,612:INFO:Huber Regressor Imported succesfully
2022-05-03 23:52:48,642:INFO:Starting cross validation
2022-05-03 23:52:48,644:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:56,729:ERROR:create_model() for huber raised an exception or returned all 0.0:
2022-05-03 23:52:56,730:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:56,731:INFO:Initializing K Neighbors Regressor
2022-05-03 23:52:56,731:INFO:Total runtime is 0.5509296377499898 minutes
2022-05-03 23:52:56,766:INFO:SubProcess create_model() called ==================================
2022-05-03 23:52:56,766:INFO:Initializing create_model()
2022-05-03 23:52:56,767:INFO:create_model(estimator=knn, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:56,767:INFO:Checking exceptions
2022-05-03 23:52:56,767:INFO:Importing libraries
2022-05-03 23:52:56,767:INFO:Copying training dataset
2022-05-03 23:52:56,777:INFO:Defining folds
2022-05-03 23:52:56,779:INFO:Declaring metric variables
2022-05-03 23:52:56,806:INFO:Importing untrained model
2022-05-03 23:52:56,834:INFO:K Neighbors Regressor Imported succesfully
2022-05-03 23:52:56,884:INFO:Starting cross validation
2022-05-03 23:52:56,886:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:52:58,463:WARNING:create_model() for knn raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:52:58,467:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:52:58,467:INFO:Initializing create_model()
2022-05-03 23:52:58,468:INFO:create_model(estimator=knn, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:52:58,468:INFO:Checking exceptions
2022-05-03 23:52:58,468:INFO:Importing libraries
2022-05-03 23:52:58,468:INFO:Copying training dataset
2022-05-03 23:52:58,471:INFO:Defining folds
2022-05-03 23:52:58,471:INFO:Declaring metric variables
2022-05-03 23:52:58,488:INFO:Importing untrained model
2022-05-03 23:52:58,510:INFO:K Neighbors Regressor Imported succesfully
2022-05-03 23:52:58,567:INFO:Starting cross validation
2022-05-03 23:52:58,568:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:53:00,576:ERROR:create_model() for knn raised an exception or returned all 0.0:
2022-05-03 23:53:00,578:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:53:00,579:INFO:Initializing Decision Tree Regressor
2022-05-03 23:53:00,580:INFO:Total runtime is 0.6150762796401977 minutes
2022-05-03 23:53:00,602:INFO:SubProcess create_model() called ==================================
2022-05-03 23:53:00,603:INFO:Initializing create_model()
2022-05-03 23:53:00,604:INFO:create_model(estimator=dt, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:53:00,605:INFO:Checking exceptions
2022-05-03 23:53:00,606:INFO:Importing libraries
2022-05-03 23:53:00,607:INFO:Copying training dataset
2022-05-03 23:53:00,610:INFO:Defining folds
2022-05-03 23:53:00,610:INFO:Declaring metric variables
2022-05-03 23:53:00,649:INFO:Importing untrained model
2022-05-03 23:53:00,680:INFO:Decision Tree Regressor Imported succesfully
2022-05-03 23:53:00,721:INFO:Starting cross validation
2022-05-03 23:53:00,722:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:53:01,580:WARNING:create_model() for dt raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:53:01,581:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:53:01,582:INFO:Initializing create_model()
2022-05-03 23:53:01,582:INFO:create_model(estimator=dt, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:53:01,582:INFO:Checking exceptions
2022-05-03 23:53:01,582:INFO:Importing libraries
2022-05-03 23:53:01,582:INFO:Copying training dataset
2022-05-03 23:53:01,584:INFO:Defining folds
2022-05-03 23:53:01,586:INFO:Declaring metric variables
2022-05-03 23:53:01,603:INFO:Importing untrained model
2022-05-03 23:53:01,620:INFO:Decision Tree Regressor Imported succesfully
2022-05-03 23:53:01,652:INFO:Starting cross validation
2022-05-03 23:53:01,654:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:53:02,508:ERROR:create_model() for dt raised an exception or returned all 0.0:
2022-05-03 23:53:02,510:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:53:02,511:INFO:Initializing Random Forest Regressor
2022-05-03 23:53:02,511:INFO:Total runtime is 0.647257645924886 minutes
2022-05-03 23:53:02,534:INFO:SubProcess create_model() called ==================================
2022-05-03 23:53:02,535:INFO:Initializing create_model()
2022-05-03 23:53:02,535:INFO:create_model(estimator=rf, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:53:02,535:INFO:Checking exceptions
2022-05-03 23:53:02,535:INFO:Importing libraries
2022-05-03 23:53:02,535:INFO:Copying training dataset
2022-05-03 23:53:02,538:INFO:Defining folds
2022-05-03 23:53:02,539:INFO:Declaring metric variables
2022-05-03 23:53:02,561:INFO:Importing untrained model
2022-05-03 23:53:02,583:INFO:Random Forest Regressor Imported succesfully
2022-05-03 23:53:02,617:INFO:Starting cross validation
2022-05-03 23:53:02,619:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:53:02,877:WARNING:create_model() for rf raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:53:02,878:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:53:02,878:INFO:Initializing create_model()
2022-05-03 23:53:02,878:INFO:create_model(estimator=rf, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:53:02,878:INFO:Checking exceptions
2022-05-03 23:53:02,879:INFO:Importing libraries
2022-05-03 23:53:02,879:INFO:Copying training dataset
2022-05-03 23:53:02,882:INFO:Defining folds
2022-05-03 23:53:02,882:INFO:Declaring metric variables
2022-05-03 23:53:02,898:INFO:Importing untrained model
2022-05-03 23:53:02,914:INFO:Random Forest Regressor Imported succesfully
2022-05-03 23:53:02,949:INFO:Starting cross validation
2022-05-03 23:53:02,951:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:53:03,225:ERROR:create_model() for rf raised an exception or returned all 0.0:
2022-05-03 23:53:03,227:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:53:03,229:INFO:Initializing Extra Trees Regressor
2022-05-03 23:53:03,229:INFO:Total runtime is 0.6592233300209045 minutes
2022-05-03 23:53:03,282:INFO:SubProcess create_model() called ==================================
2022-05-03 23:53:03,285:INFO:Initializing create_model()
2022-05-03 23:53:03,285:INFO:create_model(estimator=et, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:53:03,286:INFO:Checking exceptions
2022-05-03 23:53:03,287:INFO:Importing libraries
2022-05-03 23:53:03,287:INFO:Copying training dataset
2022-05-03 23:53:03,291:INFO:Defining folds
2022-05-03 23:53:03,292:INFO:Declaring metric variables
2022-05-03 23:53:03,314:INFO:Importing untrained model
2022-05-03 23:53:03,331:INFO:Extra Trees Regressor Imported succesfully
2022-05-03 23:53:03,368:INFO:Starting cross validation
2022-05-03 23:53:03,369:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:53:03,790:WARNING:create_model() for et raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:53:03,790:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:53:03,791:INFO:Initializing create_model()
2022-05-03 23:53:03,791:INFO:create_model(estimator=et, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:53:03,791:INFO:Checking exceptions
2022-05-03 23:53:03,791:INFO:Importing libraries
2022-05-03 23:53:03,791:INFO:Copying training dataset
2022-05-03 23:53:03,792:INFO:Defining folds
2022-05-03 23:53:03,793:INFO:Declaring metric variables
2022-05-03 23:53:03,805:INFO:Importing untrained model
2022-05-03 23:53:03,819:INFO:Extra Trees Regressor Imported succesfully
2022-05-03 23:53:03,848:INFO:Starting cross validation
2022-05-03 23:53:03,849:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:53:04,074:ERROR:create_model() for et raised an exception or returned all 0.0:
2022-05-03 23:53:04,075:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:53:04,076:INFO:Initializing AdaBoost Regressor
2022-05-03 23:53:04,076:INFO:Total runtime is 0.6733414967854817 minutes
2022-05-03 23:53:04,087:INFO:SubProcess create_model() called ==================================
2022-05-03 23:53:04,087:INFO:Initializing create_model()
2022-05-03 23:53:04,088:INFO:create_model(estimator=ada, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:53:04,088:INFO:Checking exceptions
2022-05-03 23:53:04,088:INFO:Importing libraries
2022-05-03 23:53:04,089:INFO:Copying training dataset
2022-05-03 23:53:04,091:INFO:Defining folds
2022-05-03 23:53:04,091:INFO:Declaring metric variables
2022-05-03 23:53:04,102:INFO:Importing untrained model
2022-05-03 23:53:04,115:INFO:AdaBoost Regressor Imported succesfully
2022-05-03 23:53:04,142:INFO:Starting cross validation
2022-05-03 23:53:04,143:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:53:13,177:WARNING:create_model() for ada raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:53:13,178:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:53:13,179:INFO:Initializing create_model()
2022-05-03 23:53:13,179:INFO:create_model(estimator=ada, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:53:13,179:INFO:Checking exceptions
2022-05-03 23:53:13,179:INFO:Importing libraries
2022-05-03 23:53:13,179:INFO:Copying training dataset
2022-05-03 23:53:13,186:INFO:Defining folds
2022-05-03 23:53:13,187:INFO:Declaring metric variables
2022-05-03 23:53:13,228:INFO:Importing untrained model
2022-05-03 23:53:13,256:INFO:AdaBoost Regressor Imported succesfully
2022-05-03 23:53:13,299:INFO:Starting cross validation
2022-05-03 23:53:13,300:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:53:26,232:ERROR:create_model() for ada raised an exception or returned all 0.0:
2022-05-03 23:53:26,233:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:53:26,234:INFO:Initializing Gradient Boosting Regressor
2022-05-03 23:53:26,234:INFO:Total runtime is 1.04264581600825 minutes
2022-05-03 23:53:26,250:INFO:SubProcess create_model() called ==================================
2022-05-03 23:53:26,251:INFO:Initializing create_model()
2022-05-03 23:53:26,251:INFO:create_model(estimator=gbr, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:53:26,251:INFO:Checking exceptions
2022-05-03 23:53:26,252:INFO:Importing libraries
2022-05-03 23:53:26,252:INFO:Copying training dataset
2022-05-03 23:53:26,257:INFO:Defining folds
2022-05-03 23:53:26,257:INFO:Declaring metric variables
2022-05-03 23:53:26,276:INFO:Importing untrained model
2022-05-03 23:53:26,303:INFO:Gradient Boosting Regressor Imported succesfully
2022-05-03 23:53:26,346:INFO:Starting cross validation
2022-05-03 23:53:26,350:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:53:38,715:WARNING:create_model() for gbr raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:53:38,715:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:53:38,716:INFO:Initializing create_model()
2022-05-03 23:53:38,716:INFO:create_model(estimator=gbr, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:53:38,716:INFO:Checking exceptions
2022-05-03 23:53:38,716:INFO:Importing libraries
2022-05-03 23:53:38,716:INFO:Copying training dataset
2022-05-03 23:53:38,718:INFO:Defining folds
2022-05-03 23:53:38,718:INFO:Declaring metric variables
2022-05-03 23:53:38,729:INFO:Importing untrained model
2022-05-03 23:53:38,742:INFO:Gradient Boosting Regressor Imported succesfully
2022-05-03 23:53:38,774:INFO:Starting cross validation
2022-05-03 23:53:38,777:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:53:50,702:ERROR:create_model() for gbr raised an exception or returned all 0.0:
2022-05-03 23:53:50,703:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:53:50,704:INFO:Initializing Light Gradient Boosting Machine
2022-05-03 23:53:50,704:INFO:Total runtime is 1.4504789193471272 minutes
2022-05-03 23:53:50,728:INFO:SubProcess create_model() called ==================================
2022-05-03 23:53:50,730:INFO:Initializing create_model()
2022-05-03 23:53:50,730:INFO:create_model(estimator=lightgbm, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:53:50,730:INFO:Checking exceptions
2022-05-03 23:53:50,731:INFO:Importing libraries
2022-05-03 23:53:50,731:INFO:Copying training dataset
2022-05-03 23:53:50,736:INFO:Defining folds
2022-05-03 23:53:50,737:INFO:Declaring metric variables
2022-05-03 23:53:50,756:INFO:Importing untrained model
2022-05-03 23:53:50,783:INFO:Light Gradient Boosting Machine Imported succesfully
2022-05-03 23:53:50,863:INFO:Starting cross validation
2022-05-03 23:53:50,864:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:53:53,160:WARNING:create_model() for lightgbm raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:53:53,160:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:53:53,161:INFO:Initializing create_model()
2022-05-03 23:53:53,161:INFO:create_model(estimator=lightgbm, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:53:53,161:INFO:Checking exceptions
2022-05-03 23:53:53,161:INFO:Importing libraries
2022-05-03 23:53:53,161:INFO:Copying training dataset
2022-05-03 23:53:53,163:INFO:Defining folds
2022-05-03 23:53:53,164:INFO:Declaring metric variables
2022-05-03 23:53:53,174:INFO:Importing untrained model
2022-05-03 23:53:53,196:INFO:Light Gradient Boosting Machine Imported succesfully
2022-05-03 23:53:53,225:INFO:Starting cross validation
2022-05-03 23:53:53,226:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:53:55,099:ERROR:create_model() for lightgbm raised an exception or returned all 0.0:
2022-05-03 23:53:55,100:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:53:55,101:INFO:Initializing Dummy Regressor
2022-05-03 23:53:55,101:INFO:Total runtime is 1.5237622380256652 minutes
2022-05-03 23:53:55,112:INFO:SubProcess create_model() called ==================================
2022-05-03 23:53:55,113:INFO:Initializing create_model()
2022-05-03 23:53:55,114:INFO:create_model(estimator=dummy, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:53:55,114:INFO:Checking exceptions
2022-05-03 23:53:55,115:INFO:Importing libraries
2022-05-03 23:53:55,115:INFO:Copying training dataset
2022-05-03 23:53:55,117:INFO:Defining folds
2022-05-03 23:53:55,117:INFO:Declaring metric variables
2022-05-03 23:53:55,130:INFO:Importing untrained model
2022-05-03 23:53:55,145:INFO:Dummy Regressor Imported succesfully
2022-05-03 23:53:55,180:INFO:Starting cross validation
2022-05-03 23:53:55,182:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:53:55,470:WARNING:create_model() for dummy raised an exception or returned all 0.0, trying without fit_kwargs:
2022-05-03 23:53:55,470:WARNING:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:53:55,471:INFO:Initializing create_model()
2022-05-03 23:53:55,471:INFO:create_model(estimator=dummy, fold=KFold(n_splits=10, random_state=None, shuffle=False), round=4, cross_validation=True, predict=True, fit_kwargs={}, groups=None, refit=False, verbose=False, system=False, metrics=None, add_to_model_list=True, probability_threshold=None, display=<pycaret.internal.Display.Display object at 0x000001AE66141070>, kwargs={})
2022-05-03 23:53:55,471:INFO:Checking exceptions
2022-05-03 23:53:55,471:INFO:Importing libraries
2022-05-03 23:53:55,471:INFO:Copying training dataset
2022-05-03 23:53:55,473:INFO:Defining folds
2022-05-03 23:53:55,474:INFO:Declaring metric variables
2022-05-03 23:53:55,484:INFO:Importing untrained model
2022-05-03 23:53:55,497:INFO:Dummy Regressor Imported succesfully
2022-05-03 23:53:55,531:INFO:Starting cross validation
2022-05-03 23:53:55,533:INFO:Cross validating with KFold(n_splits=10, random_state=None, shuffle=False), n_jobs=-1
2022-05-03 23:53:55,786:ERROR:create_model() for dummy raised an exception or returned all 0.0:
2022-05-03 23:53:55,787:ERROR:Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2206, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 2215, in compare_models
    model, model_fit_time = create_model_supervised(**create_model_args)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\pycaret\internal\tabular.py", line 3171, in create_model_supervised
    scores = cross_validate(
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\utils\validation.py", line 72, in inner_f
    args_msg = ", ".join(args_msg)
  File "C:\Users\dk201\anaconda3\envs\pycaret\lib\site-packages\sklearn\model_selection\_validation.py", line 256, in cross_validate
ValueError: too many values to unpack (expected 3)

2022-05-03 23:53:55,843:INFO:create_model_container: 0
2022-05-03 23:53:55,843:INFO:master_model_container: 0
2022-05-03 23:53:55,844:INFO:display_container: 2
2022-05-03 23:53:55,844:INFO:[]
2022-05-03 23:53:55,846:INFO:compare_models() succesfully completed......................................
2022-05-03 23:53:55,926:INFO:Initializing predict_model()
2022-05-03 23:53:55,926:INFO:predict_model(estimator=[], probability_threshold=None, encoded_labels=True, drift_report=False, raw_score=False, round=4, verbose=True, ml_usecase=MLUsecase.REGRESSION, display=None)
2022-05-03 23:53:55,926:INFO:Checking exceptions
2022-05-03 23:53:55,927:INFO:Preloading libraries
2022-05-03 23:53:55,927:INFO:Preparing display monitor
2022-05-04 00:01:16,016:INFO:PyCaret Supervised Module
2022-05-04 00:01:16,017:INFO:ML Usecase: regression
2022-05-04 00:01:16,017:INFO:version 2.3.6
2022-05-04 00:01:16,017:INFO:Initializing setup()
2022-05-04 00:01:16,017:INFO:setup(target=interest_rate, ml_usecase=regression, available_plots={'parameter': 'Hyperparameters', 'residuals': 'Residuals', 'error': 'Prediction Error', 'cooks': 'Cooks Distance', 'rfe': 'Feature Selection', 'learning': 'Learning Curve', 'manifold': 'Manifold Learning', 'vc': 'Validation Curve', 'feature': 'Feature Importance', 'feature_all': 'Feature Importance (All)', 'tree': 'Decision Tree', 'residuals_interactive': 'Interactive Residuals'}, train_size=0.7, test_data=None, preprocess=True, imputation_type=simple, iterative_imputation_iters=5, categorical_features=None, categorical_imputation=constant, categorical_iterative_imputer=lightgbm, ordinal_features=None, high_cardinality_features=None, high_cardinality_method=frequency, numeric_features=None, numeric_imputation=mean, numeric_iterative_imputer=lightgbm, date_features=None, ignore_features=None, normalize=False, normalize_method=zscore, transformation=False, transformation_method=yeo-johnson, handle_unknown_categorical=True, unknown_categorical_method=least_frequent, pca=False, pca_method=linear, pca_components=None, ignore_low_variance=False, combine_rare_levels=False, rare_level_threshold=0.1, bin_numeric_features=None, remove_outliers=False, outliers_threshold=0.05, remove_multicollinearity=False, multicollinearity_threshold=0.9, remove_perfect_collinearity=True, create_clusters=False, cluster_iter=20, polynomial_features=False, polynomial_degree=2, trigonometry_features=False, polynomial_threshold=0.1, group_features=None, group_names=None, feature_selection=False, feature_selection_threshold=0.8, feature_selection_method=classic, feature_interaction=False, feature_ratio=False, interaction_threshold=0.01, fix_imbalance=False, fix_imbalance_method=None, transform_target=False, transform_target_method=box-cox, data_split_shuffle=True, data_split_stratify=False, fold_strategy=kfold, fold=10, fold_shuffle=False, fold_groups=None, n_jobs=-1, use_gpu=False, custom_pipeline=None, html=True, session_id=None, log_experiment=False, experiment_name=None, log_plots=False, log_profile=False, log_data=False, silent=False, verbose=True, profile=False, profile_kwargs=None, display=None)
2022-05-04 00:01:16,018:INFO:Checking environment
2022-05-04 00:01:16,018:INFO:python_version: 3.8.12
2022-05-04 00:01:16,018:INFO:python_build: ('default', 'Oct 12 2021 03:01:40')
2022-05-04 00:01:16,018:INFO:machine: AMD64
2022-05-04 00:01:16,018:INFO:platform: Windows-10-10.0.19044-SP0
2022-05-04 00:01:16,020:WARNING:cannot find psutil installation. memory not traceable. Install psutil using pip to enable memory logging.
2022-05-04 00:01:16,020:INFO:Checking libraries
2022-05-04 00:01:16,020:INFO:pd==1.4.2
2022-05-04 00:01:16,021:INFO:numpy==1.22.3
2022-05-04 00:01:16,021:INFO:sklearn==1.0.2
